// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.5
// source: auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户模型
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // NOTE: 目前后端未单独维护, 用 created_at 占位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`                            // 必填: 密码注册
	CaptchaId     string                 `protobuf:"bytes,4,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`         // 可选: 若启用图形验证码
	CaptchaCode   string                 `protobuf:"bytes,5,opt,name=captcha_code,json=captchaCode,proto3" json:"captcha_code,omitempty"`   // 可选
	EmailCodeId   string                 `protobuf:"bytes,6,opt,name=email_code_id,json=emailCodeId,proto3" json:"email_code_id,omitempty"` // 新增: 邮箱验证码注册 (与现有 HTTP /api/auth/send-email-code 对应)
	EmailCode     string                 `protobuf:"bytes,7,opt,name=email_code,json=emailCode,proto3" json:"email_code,omitempty"`         // 新增
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *RegisterRequest) GetCaptchaCode() string {
	if x != nil {
		return x.CaptchaCode
	}
	return ""
}

func (x *RegisterRequest) GetEmailCodeId() string {
	if x != nil {
		return x.EmailCodeId
	}
	return ""
}

func (x *RegisterRequest) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

// 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // 对齐现有返回 (现行 HTTP 直接返回 token)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RegisterResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 登录请求（统一: 支持密码或邮箱验证码二选一）
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                            // 使用密码登录时必填
	EmailCodeId   string                 `protobuf:"bytes,3,opt,name=email_code_id,json=emailCodeId,proto3" json:"email_code_id,omitempty"` // 使用邮箱验证码登录: code id
	EmailCode     string                 `protobuf:"bytes,4,opt,name=email_code,json=emailCode,proto3" json:"email_code,omitempty"`         // 使用邮箱验证码登录: code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetEmailCodeId() string {
	if x != nil {
		return x.EmailCodeId
	}
	return ""
}

func (x *LoginRequest) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

// 发送登录邮箱验证码请求
type SendLoginEmailCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLoginEmailCodeRequest) Reset() {
	*x = SendLoginEmailCodeRequest{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLoginEmailCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLoginEmailCodeRequest) ProtoMessage() {}

func (x *SendLoginEmailCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLoginEmailCodeRequest.ProtoReflect.Descriptor instead.
func (*SendLoginEmailCodeRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SendLoginEmailCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendLoginEmailCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLoginEmailCodeResponse) Reset() {
	*x = SendLoginEmailCodeResponse{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLoginEmailCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLoginEmailCodeResponse) ProtoMessage() {}

func (x *SendLoginEmailCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLoginEmailCodeResponse.ProtoReflect.Descriptor instead.
func (*SendLoginEmailCodeResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SendLoginEmailCodeResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// 登录响应
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"` // 预留
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 验证令牌请求
type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 验证令牌响应
type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyTokenResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *VerifyTokenResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Deprecated: 独立邮箱验证码登录 (现已合并入 LoginRequest) 保留兼容
type EmailCodeLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailCodeLoginRequest) Reset() {
	*x = EmailCodeLoginRequest{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailCodeLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCodeLoginRequest) ProtoMessage() {}

func (x *EmailCodeLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCodeLoginRequest.ProtoReflect.Descriptor instead.
func (*EmailCodeLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *EmailCodeLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailCodeLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x0etodoing.api.v1\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe4\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x04 \x01(\tR\tcaptchaId\x12!\n" +
	"\fcaptcha_code\x18\x05 \x01(\tR\vcaptchaCode\x12\"\n" +
	"\remail_code_id\x18\x06 \x01(\tR\vemailCodeId\x12\x1d\n" +
	"\n" +
	"email_code\x18\a \x01(\tR\temailCode\"\x88\x01\n" +
	"\x10RegisterResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12(\n" +
	"\x04user\x18\x02 \x01(\v2\x14.todoing.api.v1.UserR\x04user\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x83\x01\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\"\n" +
	"\remail_code_id\x18\x03 \x01(\tR\vemailCodeId\x12\x1d\n" +
	"\n" +
	"email_code\x18\x04 \x01(\tR\temailCode\"1\n" +
	"\x19SendLoginEmailCodeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"R\n" +
	"\x1aSendLoginEmailCodeResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\"\x85\x01\n" +
	"\rLoginResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12(\n" +
	"\x04user\x18\x03 \x01(\v2\x14.todoing.api.v1.UserR\x04user\"*\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"u\n" +
	"\x13VerifyTokenResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12(\n" +
	"\x04user\x18\x02 \x01(\v2\x14.todoing.api.v1.UserR\x04user\"A\n" +
	"\x15EmailCodeLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code2\xbf\x03\n" +
	"\vAuthService\x12M\n" +
	"\bRegister\x12\x1f.todoing.api.v1.RegisterRequest\x1a .todoing.api.v1.RegisterResponse\x12D\n" +
	"\x05Login\x12\x1c.todoing.api.v1.LoginRequest\x1a\x1d.todoing.api.v1.LoginResponse\x12V\n" +
	"\x0eEmailCodeLogin\x12%.todoing.api.v1.EmailCodeLoginRequest\x1a\x1d.todoing.api.v1.LoginResponse\x12k\n" +
	"\x12SendLoginEmailCode\x12).todoing.api.v1.SendLoginEmailCodeRequest\x1a*.todoing.api.v1.SendLoginEmailCodeResponse\x12V\n" +
	"\vVerifyToken\x12\".todoing.api.v1.VerifyTokenRequest\x1a#.todoing.api.v1.VerifyTokenResponseB5Z3github.com/axfinn/todoIngPlus/backend-go/pkg/api/v1b\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_auth_proto_goTypes = []any{
	(*User)(nil),                       // 0: todoing.api.v1.User
	(*RegisterRequest)(nil),            // 1: todoing.api.v1.RegisterRequest
	(*RegisterResponse)(nil),           // 2: todoing.api.v1.RegisterResponse
	(*LoginRequest)(nil),               // 3: todoing.api.v1.LoginRequest
	(*SendLoginEmailCodeRequest)(nil),  // 4: todoing.api.v1.SendLoginEmailCodeRequest
	(*SendLoginEmailCodeResponse)(nil), // 5: todoing.api.v1.SendLoginEmailCodeResponse
	(*LoginResponse)(nil),              // 6: todoing.api.v1.LoginResponse
	(*VerifyTokenRequest)(nil),         // 7: todoing.api.v1.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),        // 8: todoing.api.v1.VerifyTokenResponse
	(*EmailCodeLoginRequest)(nil),      // 9: todoing.api.v1.EmailCodeLoginRequest
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
	(*Response)(nil),                   // 11: todoing.api.v1.Response
}
var file_auth_proto_depIdxs = []int32{
	10, // 0: todoing.api.v1.User.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: todoing.api.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: todoing.api.v1.RegisterResponse.response:type_name -> todoing.api.v1.Response
	0,  // 3: todoing.api.v1.RegisterResponse.user:type_name -> todoing.api.v1.User
	11, // 4: todoing.api.v1.SendLoginEmailCodeResponse.response:type_name -> todoing.api.v1.Response
	11, // 5: todoing.api.v1.LoginResponse.response:type_name -> todoing.api.v1.Response
	0,  // 6: todoing.api.v1.LoginResponse.user:type_name -> todoing.api.v1.User
	11, // 7: todoing.api.v1.VerifyTokenResponse.response:type_name -> todoing.api.v1.Response
	0,  // 8: todoing.api.v1.VerifyTokenResponse.user:type_name -> todoing.api.v1.User
	1,  // 9: todoing.api.v1.AuthService.Register:input_type -> todoing.api.v1.RegisterRequest
	3,  // 10: todoing.api.v1.AuthService.Login:input_type -> todoing.api.v1.LoginRequest
	9,  // 11: todoing.api.v1.AuthService.EmailCodeLogin:input_type -> todoing.api.v1.EmailCodeLoginRequest
	4,  // 12: todoing.api.v1.AuthService.SendLoginEmailCode:input_type -> todoing.api.v1.SendLoginEmailCodeRequest
	7,  // 13: todoing.api.v1.AuthService.VerifyToken:input_type -> todoing.api.v1.VerifyTokenRequest
	2,  // 14: todoing.api.v1.AuthService.Register:output_type -> todoing.api.v1.RegisterResponse
	6,  // 15: todoing.api.v1.AuthService.Login:output_type -> todoing.api.v1.LoginResponse
	6,  // 16: todoing.api.v1.AuthService.EmailCodeLogin:output_type -> todoing.api.v1.LoginResponse
	5,  // 17: todoing.api.v1.AuthService.SendLoginEmailCode:output_type -> todoing.api.v1.SendLoginEmailCodeResponse
	8,  // 18: todoing.api.v1.AuthService.VerifyToken:output_type -> todoing.api.v1.VerifyTokenResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
