// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.5
// source: dashboard.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 事件摘要
type EventSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalEvents   int64                  `protobuf:"varint,1,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	UpcomingCount int64                  `protobuf:"varint,2,opt,name=upcoming_count,json=upcomingCount,proto3" json:"upcoming_count,omitempty"`
	TodayCount    int64                  `protobuf:"varint,3,opt,name=today_count,json=todayCount,proto3" json:"today_count,omitempty"`
	TypeBreakdown map[string]int64       `protobuf:"bytes,4,rep,name=type_breakdown,json=typeBreakdown,proto3" json:"type_breakdown,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSummary) Reset() {
	*x = EventSummary{}
	mi := &file_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSummary) ProtoMessage() {}

func (x *EventSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSummary.ProtoReflect.Descriptor instead.
func (*EventSummary) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *EventSummary) GetTotalEvents() int64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *EventSummary) GetUpcomingCount() int64 {
	if x != nil {
		return x.UpcomingCount
	}
	return 0
}

func (x *EventSummary) GetTodayCount() int64 {
	if x != nil {
		return x.TodayCount
	}
	return 0
}

func (x *EventSummary) GetTypeBreakdown() map[string]int64 {
	if x != nil {
		return x.TypeBreakdown
	}
	return nil
}

// 任务摘要
type TaskSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalTasks    int64                  `protobuf:"varint,1,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CompletedRate float64                `protobuf:"fixed64,2,opt,name=completed_rate,json=completedRate,proto3" json:"completed_rate,omitempty"`
	OverdueCount  int64                  `protobuf:"varint,3,opt,name=overdue_count,json=overdueCount,proto3" json:"overdue_count,omitempty"`
	StatusCounts  map[string]int64       `protobuf:"bytes,4,rep,name=status_counts,json=statusCounts,proto3" json:"status_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSummary) Reset() {
	*x = TaskSummary{}
	mi := &file_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSummary) ProtoMessage() {}

func (x *TaskSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSummary.ProtoReflect.Descriptor instead.
func (*TaskSummary) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *TaskSummary) GetTotalTasks() int64 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *TaskSummary) GetCompletedRate() float64 {
	if x != nil {
		return x.CompletedRate
	}
	return 0
}

func (x *TaskSummary) GetOverdueCount() int64 {
	if x != nil {
		return x.OverdueCount
	}
	return 0
}

func (x *TaskSummary) GetStatusCounts() map[string]int64 {
	if x != nil {
		return x.StatusCounts
	}
	return nil
}

// Dashboard 数据聚合
type DashboardData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpcomingEvents   []*Event               `protobuf:"bytes,1,rep,name=upcoming_events,json=upcomingEvents,proto3" json:"upcoming_events,omitempty"`
	PriorityTasks    []*PriorityTask        `protobuf:"bytes,2,rep,name=priority_tasks,json=priorityTasks,proto3" json:"priority_tasks,omitempty"`
	PendingReminders []*UpcomingReminder    `protobuf:"bytes,3,rep,name=pending_reminders,json=pendingReminders,proto3" json:"pending_reminders,omitempty"` // 来自 reminder.proto 的 upcoming
	EventSummary     *EventSummary          `protobuf:"bytes,4,opt,name=event_summary,json=eventSummary,proto3" json:"event_summary,omitempty"`
	TaskSummary      *TaskSummary           `protobuf:"bytes,5,opt,name=task_summary,json=taskSummary,proto3" json:"task_summary,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DashboardData) Reset() {
	*x = DashboardData{}
	mi := &file_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardData) ProtoMessage() {}

func (x *DashboardData) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardData.ProtoReflect.Descriptor instead.
func (*DashboardData) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardData) GetUpcomingEvents() []*Event {
	if x != nil {
		return x.UpcomingEvents
	}
	return nil
}

func (x *DashboardData) GetPriorityTasks() []*PriorityTask {
	if x != nil {
		return x.PriorityTasks
	}
	return nil
}

func (x *DashboardData) GetPendingReminders() []*UpcomingReminder {
	if x != nil {
		return x.PendingReminders
	}
	return nil
}

func (x *DashboardData) GetEventSummary() *EventSummary {
	if x != nil {
		return x.EventSummary
	}
	return nil
}

func (x *DashboardData) GetTaskSummary() *TaskSummary {
	if x != nil {
		return x.TaskSummary
	}
	return nil
}

type GetDashboardDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardDataRequest) Reset() {
	*x = GetDashboardDataRequest{}
	mi := &file_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardDataRequest) ProtoMessage() {}

func (x *GetDashboardDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardDataRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardDataRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{3}
}

type GetDashboardDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Data          *DashboardData         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardDataResponse) Reset() {
	*x = GetDashboardDataResponse{}
	mi := &file_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardDataResponse) ProtoMessage() {}

func (x *GetDashboardDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardDataResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardDataResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *GetDashboardDataResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetDashboardDataResponse) GetData() *DashboardData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPriorityTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriorityTasksRequest) Reset() {
	*x = GetPriorityTasksRequest{}
	mi := &file_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriorityTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriorityTasksRequest) ProtoMessage() {}

func (x *GetPriorityTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriorityTasksRequest.ProtoReflect.Descriptor instead.
func (*GetPriorityTasksRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{5}
}

type GetPriorityTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Tasks         []*PriorityTask        `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriorityTasksResponse) Reset() {
	*x = GetPriorityTasksResponse{}
	mi := &file_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriorityTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriorityTasksResponse) ProtoMessage() {}

func (x *GetPriorityTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriorityTasksResponse.ProtoReflect.Descriptor instead.
func (*GetPriorityTasksResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *GetPriorityTasksResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetPriorityTasksResponse) GetTasks() []*PriorityTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *GetPriorityTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x0fdashboard.proto\x12\x0etodoing.api.v1\x1a\fcommon.proto\x1a\n" +
	"task.proto\x1a\vevent.proto\x1a\x0ereminder.proto\"\x93\x02\n" +
	"\fEventSummary\x12!\n" +
	"\ftotal_events\x18\x01 \x01(\x03R\vtotalEvents\x12%\n" +
	"\x0eupcoming_count\x18\x02 \x01(\x03R\rupcomingCount\x12\x1f\n" +
	"\vtoday_count\x18\x03 \x01(\x03R\n" +
	"todayCount\x12V\n" +
	"\x0etype_breakdown\x18\x04 \x03(\v2/.todoing.api.v1.EventSummary.TypeBreakdownEntryR\rtypeBreakdown\x1a@\n" +
	"\x12TypeBreakdownEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x8f\x02\n" +
	"\vTaskSummary\x12\x1f\n" +
	"\vtotal_tasks\x18\x01 \x01(\x03R\n" +
	"totalTasks\x12%\n" +
	"\x0ecompleted_rate\x18\x02 \x01(\x01R\rcompletedRate\x12#\n" +
	"\roverdue_count\x18\x03 \x01(\x03R\foverdueCount\x12R\n" +
	"\rstatus_counts\x18\x04 \x03(\v2-.todoing.api.v1.TaskSummary.StatusCountsEntryR\fstatusCounts\x1a?\n" +
	"\x11StatusCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xe6\x02\n" +
	"\rDashboardData\x12>\n" +
	"\x0fupcoming_events\x18\x01 \x03(\v2\x15.todoing.api.v1.EventR\x0eupcomingEvents\x12C\n" +
	"\x0epriority_tasks\x18\x02 \x03(\v2\x1c.todoing.api.v1.PriorityTaskR\rpriorityTasks\x12M\n" +
	"\x11pending_reminders\x18\x03 \x03(\v2 .todoing.api.v1.UpcomingReminderR\x10pendingReminders\x12A\n" +
	"\revent_summary\x18\x04 \x01(\v2\x1c.todoing.api.v1.EventSummaryR\feventSummary\x12>\n" +
	"\ftask_summary\x18\x05 \x01(\v2\x1b.todoing.api.v1.TaskSummaryR\vtaskSummary\"\x19\n" +
	"\x17GetDashboardDataRequest\"\x83\x01\n" +
	"\x18GetDashboardDataResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x121\n" +
	"\x04data\x18\x02 \x01(\v2\x1d.todoing.api.v1.DashboardDataR\x04data\"\x19\n" +
	"\x17GetPriorityTasksRequest\"\x9a\x01\n" +
	"\x18GetPriorityTasksResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x122\n" +
	"\x05tasks\x18\x02 \x03(\v2\x1c.todoing.api.v1.PriorityTaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total2\xe0\x01\n" +
	"\x10DashboardService\x12e\n" +
	"\x10GetDashboardData\x12'.todoing.api.v1.GetDashboardDataRequest\x1a(.todoing.api.v1.GetDashboardDataResponse\x12e\n" +
	"\x10GetPriorityTasks\x12'.todoing.api.v1.GetPriorityTasksRequest\x1a(.todoing.api.v1.GetPriorityTasksResponseB5Z3github.com/axfinn/todoIngPlus/backend-go/pkg/api/v1b\x06proto3"

var (
	file_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_proto_rawDescData []byte
)

func file_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)))
	})
	return file_dashboard_proto_rawDescData
}

var file_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_dashboard_proto_goTypes = []any{
	(*EventSummary)(nil),             // 0: todoing.api.v1.EventSummary
	(*TaskSummary)(nil),              // 1: todoing.api.v1.TaskSummary
	(*DashboardData)(nil),            // 2: todoing.api.v1.DashboardData
	(*GetDashboardDataRequest)(nil),  // 3: todoing.api.v1.GetDashboardDataRequest
	(*GetDashboardDataResponse)(nil), // 4: todoing.api.v1.GetDashboardDataResponse
	(*GetPriorityTasksRequest)(nil),  // 5: todoing.api.v1.GetPriorityTasksRequest
	(*GetPriorityTasksResponse)(nil), // 6: todoing.api.v1.GetPriorityTasksResponse
	nil,                              // 7: todoing.api.v1.EventSummary.TypeBreakdownEntry
	nil,                              // 8: todoing.api.v1.TaskSummary.StatusCountsEntry
	(*Event)(nil),                    // 9: todoing.api.v1.Event
	(*PriorityTask)(nil),             // 10: todoing.api.v1.PriorityTask
	(*UpcomingReminder)(nil),         // 11: todoing.api.v1.UpcomingReminder
	(*Response)(nil),                 // 12: todoing.api.v1.Response
}
var file_dashboard_proto_depIdxs = []int32{
	7,  // 0: todoing.api.v1.EventSummary.type_breakdown:type_name -> todoing.api.v1.EventSummary.TypeBreakdownEntry
	8,  // 1: todoing.api.v1.TaskSummary.status_counts:type_name -> todoing.api.v1.TaskSummary.StatusCountsEntry
	9,  // 2: todoing.api.v1.DashboardData.upcoming_events:type_name -> todoing.api.v1.Event
	10, // 3: todoing.api.v1.DashboardData.priority_tasks:type_name -> todoing.api.v1.PriorityTask
	11, // 4: todoing.api.v1.DashboardData.pending_reminders:type_name -> todoing.api.v1.UpcomingReminder
	0,  // 5: todoing.api.v1.DashboardData.event_summary:type_name -> todoing.api.v1.EventSummary
	1,  // 6: todoing.api.v1.DashboardData.task_summary:type_name -> todoing.api.v1.TaskSummary
	12, // 7: todoing.api.v1.GetDashboardDataResponse.response:type_name -> todoing.api.v1.Response
	2,  // 8: todoing.api.v1.GetDashboardDataResponse.data:type_name -> todoing.api.v1.DashboardData
	12, // 9: todoing.api.v1.GetPriorityTasksResponse.response:type_name -> todoing.api.v1.Response
	10, // 10: todoing.api.v1.GetPriorityTasksResponse.tasks:type_name -> todoing.api.v1.PriorityTask
	3,  // 11: todoing.api.v1.DashboardService.GetDashboardData:input_type -> todoing.api.v1.GetDashboardDataRequest
	5,  // 12: todoing.api.v1.DashboardService.GetPriorityTasks:input_type -> todoing.api.v1.GetPriorityTasksRequest
	4,  // 13: todoing.api.v1.DashboardService.GetDashboardData:output_type -> todoing.api.v1.GetDashboardDataResponse
	6,  // 14: todoing.api.v1.DashboardService.GetPriorityTasks:output_type -> todoing.api.v1.GetPriorityTasksResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_dashboard_proto_init() }
func file_dashboard_proto_init() {
	if File_dashboard_proto != nil {
		return
	}
	file_common_proto_init()
	file_task_proto_init()
	file_event_proto_init()
	file_reminder_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_proto = out.File
	file_dashboard_proto_goTypes = nil
	file_dashboard_proto_depIdxs = nil
}
