// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.5
// source: notification.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EventId       string                 `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // optional
	IsRead        bool                   `protobuf:"varint,5,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	ReadAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNotificationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateNotificationRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type CreateNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Notification  *Notification          `protobuf:"bytes,2,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationResponse) Reset() {
	*x = CreateNotificationResponse{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationResponse) ProtoMessage() {}

func (x *CreateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationResponse.ProtoReflect.Descriptor instead.
func (*CreateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNotificationResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadOnly    bool                   `protobuf:"varint,1,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ListNotificationsRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

func (x *ListNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Notifications []*Notification        `protobuf:"bytes,2,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ListNotificationsResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MarkNotificationReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationReadRequest) Reset() {
	*x = MarkNotificationReadRequest{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReadRequest) ProtoMessage() {}

func (x *MarkNotificationReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *MarkNotificationReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MarkNotificationReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationReadResponse) Reset() {
	*x = MarkNotificationReadResponse{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReadResponse) ProtoMessage() {}

func (x *MarkNotificationReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReadResponse.ProtoReflect.Descriptor instead.
func (*MarkNotificationReadResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *MarkNotificationReadResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MarkNotificationReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MarkAllNotificationsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsReadRequest) Reset() {
	*x = MarkAllNotificationsReadRequest{}
	mi := &file_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsReadRequest) ProtoMessage() {}

func (x *MarkAllNotificationsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{7}
}

type MarkAllNotificationsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Modified      int64                  `protobuf:"varint,2,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsReadResponse) Reset() {
	*x = MarkAllNotificationsReadResponse{}
	mi := &file_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsReadResponse) ProtoMessage() {}

func (x *MarkAllNotificationsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsReadResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{8}
}

func (x *MarkAllNotificationsReadResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MarkAllNotificationsReadResponse) GetModified() int64 {
	if x != nil {
		return x.Modified
	}
	return 0
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\x0etodoing.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xf5\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12\x17\n" +
	"\ais_read\x18\x05 \x01(\bR\x06isRead\x123\n" +
	"\aread_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06readAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12F\n" +
	"\bmetadata\x18\b \x03(\v2*.todoing.api.v1.Notification.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x19CreateNotificationRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"\x94\x01\n" +
	"\x1aCreateNotificationResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12@\n" +
	"\fnotification\x18\x02 \x01(\v2\x1c.todoing.api.v1.NotificationR\fnotification\"Q\n" +
	"\x18ListNotificationsRequest\x12\x1f\n" +
	"\vunread_only\x18\x01 \x01(\bR\n" +
	"unreadOnly\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xab\x01\n" +
	"\x19ListNotificationsResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12B\n" +
	"\rnotifications\x18\x02 \x03(\v2\x1c.todoing.api.v1.NotificationR\rnotifications\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"-\n" +
	"\x1bMarkNotificationReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x1cMarkNotificationReadResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"!\n" +
	"\x1fMarkAllNotificationsReadRequest\"t\n" +
	" MarkAllNotificationsReadResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12\x1a\n" +
	"\bmodified\x18\x02 \x01(\x03R\bmodified2\xde\x03\n" +
	"\x13NotificationService\x12k\n" +
	"\x12CreateNotification\x12).todoing.api.v1.CreateNotificationRequest\x1a*.todoing.api.v1.CreateNotificationResponse\x12h\n" +
	"\x11ListNotifications\x12(.todoing.api.v1.ListNotificationsRequest\x1a).todoing.api.v1.ListNotificationsResponse\x12q\n" +
	"\x14MarkNotificationRead\x12+.todoing.api.v1.MarkNotificationReadRequest\x1a,.todoing.api.v1.MarkNotificationReadResponse\x12}\n" +
	"\x18MarkAllNotificationsRead\x12/.todoing.api.v1.MarkAllNotificationsReadRequest\x1a0.todoing.api.v1.MarkAllNotificationsReadResponseB5Z3github.com/axfinn/todoIngPlus/backend-go/pkg/api/v1b\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_notification_proto_goTypes = []any{
	(*Notification)(nil),                     // 0: todoing.api.v1.Notification
	(*CreateNotificationRequest)(nil),        // 1: todoing.api.v1.CreateNotificationRequest
	(*CreateNotificationResponse)(nil),       // 2: todoing.api.v1.CreateNotificationResponse
	(*ListNotificationsRequest)(nil),         // 3: todoing.api.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),        // 4: todoing.api.v1.ListNotificationsResponse
	(*MarkNotificationReadRequest)(nil),      // 5: todoing.api.v1.MarkNotificationReadRequest
	(*MarkNotificationReadResponse)(nil),     // 6: todoing.api.v1.MarkNotificationReadResponse
	(*MarkAllNotificationsReadRequest)(nil),  // 7: todoing.api.v1.MarkAllNotificationsReadRequest
	(*MarkAllNotificationsReadResponse)(nil), // 8: todoing.api.v1.MarkAllNotificationsReadResponse
	nil,                                      // 9: todoing.api.v1.Notification.MetadataEntry
	(*timestamppb.Timestamp)(nil),            // 10: google.protobuf.Timestamp
	(*Response)(nil),                         // 11: todoing.api.v1.Response
}
var file_notification_proto_depIdxs = []int32{
	10, // 0: todoing.api.v1.Notification.read_at:type_name -> google.protobuf.Timestamp
	10, // 1: todoing.api.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: todoing.api.v1.Notification.metadata:type_name -> todoing.api.v1.Notification.MetadataEntry
	11, // 3: todoing.api.v1.CreateNotificationResponse.response:type_name -> todoing.api.v1.Response
	0,  // 4: todoing.api.v1.CreateNotificationResponse.notification:type_name -> todoing.api.v1.Notification
	11, // 5: todoing.api.v1.ListNotificationsResponse.response:type_name -> todoing.api.v1.Response
	0,  // 6: todoing.api.v1.ListNotificationsResponse.notifications:type_name -> todoing.api.v1.Notification
	11, // 7: todoing.api.v1.MarkNotificationReadResponse.response:type_name -> todoing.api.v1.Response
	11, // 8: todoing.api.v1.MarkAllNotificationsReadResponse.response:type_name -> todoing.api.v1.Response
	1,  // 9: todoing.api.v1.NotificationService.CreateNotification:input_type -> todoing.api.v1.CreateNotificationRequest
	3,  // 10: todoing.api.v1.NotificationService.ListNotifications:input_type -> todoing.api.v1.ListNotificationsRequest
	5,  // 11: todoing.api.v1.NotificationService.MarkNotificationRead:input_type -> todoing.api.v1.MarkNotificationReadRequest
	7,  // 12: todoing.api.v1.NotificationService.MarkAllNotificationsRead:input_type -> todoing.api.v1.MarkAllNotificationsReadRequest
	2,  // 13: todoing.api.v1.NotificationService.CreateNotification:output_type -> todoing.api.v1.CreateNotificationResponse
	4,  // 14: todoing.api.v1.NotificationService.ListNotifications:output_type -> todoing.api.v1.ListNotificationsResponse
	6,  // 15: todoing.api.v1.NotificationService.MarkNotificationRead:output_type -> todoing.api.v1.MarkNotificationReadResponse
	8,  // 16: todoing.api.v1.NotificationService.MarkAllNotificationsRead:output_type -> todoing.api.v1.MarkAllNotificationsReadResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
