// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.5
// source: reminder.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 提醒类型
type ReminderType int32

const (
	ReminderType_REMINDER_TYPE_UNSPECIFIED ReminderType = 0
	ReminderType_REMINDER_TYPE_APP         ReminderType = 1 // app (SSE)
	ReminderType_REMINDER_TYPE_EMAIL       ReminderType = 2 // email
	ReminderType_REMINDER_TYPE_BOTH        ReminderType = 3 // both
)

// Enum value maps for ReminderType.
var (
	ReminderType_name = map[int32]string{
		0: "REMINDER_TYPE_UNSPECIFIED",
		1: "REMINDER_TYPE_APP",
		2: "REMINDER_TYPE_EMAIL",
		3: "REMINDER_TYPE_BOTH",
	}
	ReminderType_value = map[string]int32{
		"REMINDER_TYPE_UNSPECIFIED": 0,
		"REMINDER_TYPE_APP":         1,
		"REMINDER_TYPE_EMAIL":       2,
		"REMINDER_TYPE_BOTH":        3,
	}
)

func (x ReminderType) Enum() *ReminderType {
	p := new(ReminderType)
	*p = x
	return p
}

func (x ReminderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReminderType) Descriptor() protoreflect.EnumDescriptor {
	return file_reminder_proto_enumTypes[0].Descriptor()
}

func (ReminderType) Type() protoreflect.EnumType {
	return &file_reminder_proto_enumTypes[0]
}

func (x ReminderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReminderType.Descriptor instead.
func (ReminderType) EnumDescriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{0}
}

// 提醒
type Reminder struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                   `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AdvanceDays   int32                    `protobuf:"varint,4,opt,name=advance_days,json=advanceDays,proto3" json:"advance_days,omitempty"`
	ReminderTimes []string                 `protobuf:"bytes,5,rep,name=reminder_times,json=reminderTimes,proto3" json:"reminder_times,omitempty"` // HH:MM
	AbsoluteTimes []*timestamppb.Timestamp `protobuf:"bytes,6,rep,name=absolute_times,json=absoluteTimes,proto3" json:"absolute_times,omitempty"` // 与后端 AbsoluteTimes 对齐
	ReminderType  ReminderType             `protobuf:"varint,7,opt,name=reminder_type,json=reminderType,proto3,enum=todoing.api.v1.ReminderType" json:"reminder_type,omitempty"`
	CustomMessage string                   `protobuf:"bytes,8,opt,name=custom_message,json=customMessage,proto3" json:"custom_message,omitempty"`
	IsActive      bool                     `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	LastSent      *timestamppb.Timestamp   `protobuf:"bytes,10,opt,name=last_sent,json=lastSent,proto3" json:"last_sent,omitempty"`
	NextSend      *timestamppb.Timestamp   `protobuf:"bytes,11,opt,name=next_send,json=nextSend,proto3" json:"next_send,omitempty"`
	CreatedAt     *timestamppb.Timestamp   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp   `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reminder) Reset() {
	*x = Reminder{}
	mi := &file_reminder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reminder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reminder) ProtoMessage() {}

func (x *Reminder) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reminder.ProtoReflect.Descriptor instead.
func (*Reminder) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{0}
}

func (x *Reminder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reminder) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Reminder) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reminder) GetAdvanceDays() int32 {
	if x != nil {
		return x.AdvanceDays
	}
	return 0
}

func (x *Reminder) GetReminderTimes() []string {
	if x != nil {
		return x.ReminderTimes
	}
	return nil
}

func (x *Reminder) GetAbsoluteTimes() []*timestamppb.Timestamp {
	if x != nil {
		return x.AbsoluteTimes
	}
	return nil
}

func (x *Reminder) GetReminderType() ReminderType {
	if x != nil {
		return x.ReminderType
	}
	return ReminderType_REMINDER_TYPE_UNSPECIFIED
}

func (x *Reminder) GetCustomMessage() string {
	if x != nil {
		return x.CustomMessage
	}
	return ""
}

func (x *Reminder) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Reminder) GetLastSent() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSent
	}
	return nil
}

func (x *Reminder) GetNextSend() *timestamppb.Timestamp {
	if x != nil {
		return x.NextSend
	}
	return nil
}

func (x *Reminder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Reminder) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 包含事件的提醒
type ReminderWithEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reminder      *Reminder              `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReminderWithEvent) Reset() {
	*x = ReminderWithEvent{}
	mi := &file_reminder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReminderWithEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderWithEvent) ProtoMessage() {}

func (x *ReminderWithEvent) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderWithEvent.ProtoReflect.Descriptor instead.
func (*ReminderWithEvent) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{1}
}

func (x *ReminderWithEvent) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

func (x *ReminderWithEvent) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// 创建
type CreateReminderRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	EventId       string                   `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AdvanceDays   int32                    `protobuf:"varint,2,opt,name=advance_days,json=advanceDays,proto3" json:"advance_days,omitempty"`
	ReminderTimes []string                 `protobuf:"bytes,3,rep,name=reminder_times,json=reminderTimes,proto3" json:"reminder_times,omitempty"`
	AbsoluteTimes []*timestamppb.Timestamp `protobuf:"bytes,4,rep,name=absolute_times,json=absoluteTimes,proto3" json:"absolute_times,omitempty"` // 二选一: 与 times 互斥
	ReminderType  ReminderType             `protobuf:"varint,5,opt,name=reminder_type,json=reminderType,proto3,enum=todoing.api.v1.ReminderType" json:"reminder_type,omitempty"`
	CustomMessage string                   `protobuf:"bytes,6,opt,name=custom_message,json=customMessage,proto3" json:"custom_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReminderRequest) Reset() {
	*x = CreateReminderRequest{}
	mi := &file_reminder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReminderRequest) ProtoMessage() {}

func (x *CreateReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReminderRequest.ProtoReflect.Descriptor instead.
func (*CreateReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReminderRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateReminderRequest) GetAdvanceDays() int32 {
	if x != nil {
		return x.AdvanceDays
	}
	return 0
}

func (x *CreateReminderRequest) GetReminderTimes() []string {
	if x != nil {
		return x.ReminderTimes
	}
	return nil
}

func (x *CreateReminderRequest) GetAbsoluteTimes() []*timestamppb.Timestamp {
	if x != nil {
		return x.AbsoluteTimes
	}
	return nil
}

func (x *CreateReminderRequest) GetReminderType() ReminderType {
	if x != nil {
		return x.ReminderType
	}
	return ReminderType_REMINDER_TYPE_UNSPECIFIED
}

func (x *CreateReminderRequest) GetCustomMessage() string {
	if x != nil {
		return x.CustomMessage
	}
	return ""
}

type CreateReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Reminder      *Reminder              `protobuf:"bytes,2,opt,name=reminder,proto3" json:"reminder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReminderResponse) Reset() {
	*x = CreateReminderResponse{}
	mi := &file_reminder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReminderResponse) ProtoMessage() {}

func (x *CreateReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReminderResponse.ProtoReflect.Descriptor instead.
func (*CreateReminderResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReminderResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateReminderResponse) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

// 获取单个
type GetReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReminderRequest) Reset() {
	*x = GetReminderRequest{}
	mi := &file_reminder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderRequest) ProtoMessage() {}

func (x *GetReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderRequest.ProtoReflect.Descriptor instead.
func (*GetReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{4}
}

func (x *GetReminderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Reminder      *ReminderWithEvent     `protobuf:"bytes,2,opt,name=reminder,proto3" json:"reminder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReminderResponse) Reset() {
	*x = GetReminderResponse{}
	mi := &file_reminder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderResponse) ProtoMessage() {}

func (x *GetReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderResponse.ProtoReflect.Descriptor instead.
func (*GetReminderResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{5}
}

func (x *GetReminderResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetReminderResponse) GetReminder() *ReminderWithEvent {
	if x != nil {
		return x.Reminder
	}
	return nil
}

// 更新（全部可选）
type UpdateReminderRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdvanceDays   int32                    `protobuf:"varint,2,opt,name=advance_days,json=advanceDays,proto3" json:"advance_days,omitempty"` // 0 表示更新为 0；不传表示不修改
	ReminderTimes []string                 `protobuf:"bytes,3,rep,name=reminder_times,json=reminderTimes,proto3" json:"reminder_times,omitempty"`
	AbsoluteTimes []*timestamppb.Timestamp `protobuf:"bytes,4,rep,name=absolute_times,json=absoluteTimes,proto3" json:"absolute_times,omitempty"`
	ReminderType  ReminderType             `protobuf:"varint,5,opt,name=reminder_type,json=reminderType,proto3,enum=todoing.api.v1.ReminderType" json:"reminder_type,omitempty"`
	CustomMessage string                   `protobuf:"bytes,6,opt,name=custom_message,json=customMessage,proto3" json:"custom_message,omitempty"`
	IsActive      bool                     `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReminderRequest) Reset() {
	*x = UpdateReminderRequest{}
	mi := &file_reminder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReminderRequest) ProtoMessage() {}

func (x *UpdateReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReminderRequest.ProtoReflect.Descriptor instead.
func (*UpdateReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateReminderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateReminderRequest) GetAdvanceDays() int32 {
	if x != nil {
		return x.AdvanceDays
	}
	return 0
}

func (x *UpdateReminderRequest) GetReminderTimes() []string {
	if x != nil {
		return x.ReminderTimes
	}
	return nil
}

func (x *UpdateReminderRequest) GetAbsoluteTimes() []*timestamppb.Timestamp {
	if x != nil {
		return x.AbsoluteTimes
	}
	return nil
}

func (x *UpdateReminderRequest) GetReminderType() ReminderType {
	if x != nil {
		return x.ReminderType
	}
	return ReminderType_REMINDER_TYPE_UNSPECIFIED
}

func (x *UpdateReminderRequest) GetCustomMessage() string {
	if x != nil {
		return x.CustomMessage
	}
	return ""
}

func (x *UpdateReminderRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Reminder      *Reminder              `protobuf:"bytes,2,opt,name=reminder,proto3" json:"reminder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReminderResponse) Reset() {
	*x = UpdateReminderResponse{}
	mi := &file_reminder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReminderResponse) ProtoMessage() {}

func (x *UpdateReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReminderResponse.ProtoReflect.Descriptor instead.
func (*UpdateReminderResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateReminderResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *UpdateReminderResponse) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

// 删除
type DeleteReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReminderRequest) Reset() {
	*x = DeleteReminderRequest{}
	mi := &file_reminder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReminderRequest) ProtoMessage() {}

func (x *DeleteReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReminderRequest.ProtoReflect.Descriptor instead.
func (*DeleteReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteReminderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 列表
type ListRemindersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemindersRequest) Reset() {
	*x = ListRemindersRequest{}
	mi := &file_reminder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemindersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemindersRequest) ProtoMessage() {}

func (x *ListRemindersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemindersRequest.ProtoReflect.Descriptor instead.
func (*ListRemindersRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{9}
}

func (x *ListRemindersRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListRemindersRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListRemindersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Reminders     []*ReminderWithEvent   `protobuf:"bytes,2,rep,name=reminders,proto3" json:"reminders,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemindersResponse) Reset() {
	*x = ListRemindersResponse{}
	mi := &file_reminder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemindersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemindersResponse) ProtoMessage() {}

func (x *ListRemindersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemindersResponse.ProtoReflect.Descriptor instead.
func (*ListRemindersResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{10}
}

func (x *ListRemindersResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListRemindersResponse) GetReminders() []*ReminderWithEvent {
	if x != nil {
		return x.Reminders
	}
	return nil
}

func (x *ListRemindersResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 精简列表 (无分页)
type ListSimpleRemindersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSimpleRemindersRequest) Reset() {
	*x = ListSimpleRemindersRequest{}
	mi := &file_reminder_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSimpleRemindersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSimpleRemindersRequest) ProtoMessage() {}

func (x *ListSimpleRemindersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSimpleRemindersRequest.ProtoReflect.Descriptor instead.
func (*ListSimpleRemindersRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{11}
}

func (x *ListSimpleRemindersRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListSimpleRemindersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSimpleRemindersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Reminders     []*Reminder            `protobuf:"bytes,2,rep,name=reminders,proto3" json:"reminders,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSimpleRemindersResponse) Reset() {
	*x = ListSimpleRemindersResponse{}
	mi := &file_reminder_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSimpleRemindersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSimpleRemindersResponse) ProtoMessage() {}

func (x *ListSimpleRemindersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSimpleRemindersResponse.ProtoReflect.Descriptor instead.
func (*ListSimpleRemindersResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{12}
}

func (x *ListSimpleRemindersResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListSimpleRemindersResponse) GetReminders() []*Reminder {
	if x != nil {
		return x.Reminders
	}
	return nil
}

func (x *ListSimpleRemindersResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 即将到来的提醒
type UpcomingReminder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventTitle    string                 `protobuf:"bytes,2,opt,name=event_title,json=eventTitle,proto3" json:"event_title,omitempty"`
	EventDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	DaysLeft      int32                  `protobuf:"varint,5,opt,name=days_left,json=daysLeft,proto3" json:"days_left,omitempty"`
	Importance    int32                  `protobuf:"varint,6,opt,name=importance,proto3" json:"importance,omitempty"`
	ReminderAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=reminder_at,json=reminderAt,proto3" json:"reminder_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpcomingReminder) Reset() {
	*x = UpcomingReminder{}
	mi := &file_reminder_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcomingReminder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingReminder) ProtoMessage() {}

func (x *UpcomingReminder) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingReminder.ProtoReflect.Descriptor instead.
func (*UpcomingReminder) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{13}
}

func (x *UpcomingReminder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpcomingReminder) GetEventTitle() string {
	if x != nil {
		return x.EventTitle
	}
	return ""
}

func (x *UpcomingReminder) GetEventDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EventDate
	}
	return nil
}

func (x *UpcomingReminder) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpcomingReminder) GetDaysLeft() int32 {
	if x != nil {
		return x.DaysLeft
	}
	return 0
}

func (x *UpcomingReminder) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *UpcomingReminder) GetReminderAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReminderAt
	}
	return nil
}

type GetUpcomingRemindersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hours         int32                  `protobuf:"varint,1,opt,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingRemindersRequest) Reset() {
	*x = GetUpcomingRemindersRequest{}
	mi := &file_reminder_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingRemindersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingRemindersRequest) ProtoMessage() {}

func (x *GetUpcomingRemindersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingRemindersRequest.ProtoReflect.Descriptor instead.
func (*GetUpcomingRemindersRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{14}
}

func (x *GetUpcomingRemindersRequest) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

type GetUpcomingRemindersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Reminders     []*UpcomingReminder    `protobuf:"bytes,2,rep,name=reminders,proto3" json:"reminders,omitempty"`
	Hours         int32                  `protobuf:"varint,3,opt,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingRemindersResponse) Reset() {
	*x = GetUpcomingRemindersResponse{}
	mi := &file_reminder_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingRemindersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingRemindersResponse) ProtoMessage() {}

func (x *GetUpcomingRemindersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingRemindersResponse.ProtoReflect.Descriptor instead.
func (*GetUpcomingRemindersResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{15}
}

func (x *GetUpcomingRemindersResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetUpcomingRemindersResponse) GetReminders() []*UpcomingReminder {
	if x != nil {
		return x.Reminders
	}
	return nil
}

func (x *GetUpcomingRemindersResponse) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

// 预览提醒计划（不落库）
type PreviewReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AdvanceDays   int32                  `protobuf:"varint,2,opt,name=advance_days,json=advanceDays,proto3" json:"advance_days,omitempty"`
	ReminderTimes []string               `protobuf:"bytes,3,rep,name=reminder_times,json=reminderTimes,proto3" json:"reminder_times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewReminderRequest) Reset() {
	*x = PreviewReminderRequest{}
	mi := &file_reminder_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewReminderRequest) ProtoMessage() {}

func (x *PreviewReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewReminderRequest.ProtoReflect.Descriptor instead.
func (*PreviewReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{16}
}

func (x *PreviewReminderRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PreviewReminderRequest) GetAdvanceDays() int32 {
	if x != nil {
		return x.AdvanceDays
	}
	return 0
}

func (x *PreviewReminderRequest) GetReminderTimes() []string {
	if x != nil {
		return x.ReminderTimes
	}
	return nil
}

type PreviewReminderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReminderAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=reminder_at,json=reminderAt,proto3" json:"reminder_at,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewReminderItem) Reset() {
	*x = PreviewReminderItem{}
	mi := &file_reminder_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewReminderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewReminderItem) ProtoMessage() {}

func (x *PreviewReminderItem) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewReminderItem.ProtoReflect.Descriptor instead.
func (*PreviewReminderItem) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{17}
}

func (x *PreviewReminderItem) GetReminderAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReminderAt
	}
	return nil
}

func (x *PreviewReminderItem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PreviewReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Schedule      []*PreviewReminderItem `protobuf:"bytes,2,rep,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewReminderResponse) Reset() {
	*x = PreviewReminderResponse{}
	mi := &file_reminder_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewReminderResponse) ProtoMessage() {}

func (x *PreviewReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewReminderResponse.ProtoReflect.Descriptor instead.
func (*PreviewReminderResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{18}
}

func (x *PreviewReminderResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PreviewReminderResponse) GetSchedule() []*PreviewReminderItem {
	if x != nil {
		return x.Schedule
	}
	return nil
}

// Snooze
type SnoozeReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SnoozeMinutes int32                  `protobuf:"varint,2,opt,name=snooze_minutes,json=snoozeMinutes,proto3" json:"snooze_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnoozeReminderRequest) Reset() {
	*x = SnoozeReminderRequest{}
	mi := &file_reminder_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnoozeReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnoozeReminderRequest) ProtoMessage() {}

func (x *SnoozeReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnoozeReminderRequest.ProtoReflect.Descriptor instead.
func (*SnoozeReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{19}
}

func (x *SnoozeReminderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnoozeReminderRequest) GetSnoozeMinutes() int32 {
	if x != nil {
		return x.SnoozeMinutes
	}
	return 0
}

type SnoozeReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	SnoozeMinutes int32                  `protobuf:"varint,2,opt,name=snooze_minutes,json=snoozeMinutes,proto3" json:"snooze_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnoozeReminderResponse) Reset() {
	*x = SnoozeReminderResponse{}
	mi := &file_reminder_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnoozeReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnoozeReminderResponse) ProtoMessage() {}

func (x *SnoozeReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnoozeReminderResponse.ProtoReflect.Descriptor instead.
func (*SnoozeReminderResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{20}
}

func (x *SnoozeReminderResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SnoozeReminderResponse) GetSnoozeMinutes() int32 {
	if x != nil {
		return x.SnoozeMinutes
	}
	return 0
}

// Toggle Active
type ToggleReminderActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleReminderActiveRequest) Reset() {
	*x = ToggleReminderActiveRequest{}
	mi := &file_reminder_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleReminderActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleReminderActiveRequest) ProtoMessage() {}

func (x *ToggleReminderActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleReminderActiveRequest.ProtoReflect.Descriptor instead.
func (*ToggleReminderActiveRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{21}
}

func (x *ToggleReminderActiveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ToggleReminderActiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleReminderActiveResponse) Reset() {
	*x = ToggleReminderActiveResponse{}
	mi := &file_reminder_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleReminderActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleReminderActiveResponse) ProtoMessage() {}

func (x *ToggleReminderActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleReminderActiveResponse.ProtoReflect.Descriptor instead.
func (*ToggleReminderActiveResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{22}
}

func (x *ToggleReminderActiveResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ToggleReminderActiveResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// 创建测试提醒
type CreateTestReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // 可空：后端自动挑选
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DelaySeconds  int32                  `protobuf:"varint,3,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	SendEmail     bool                   `protobuf:"varint,4,opt,name=send_email,json=sendEmail,proto3" json:"send_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTestReminderRequest) Reset() {
	*x = CreateTestReminderRequest{}
	mi := &file_reminder_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTestReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestReminderRequest) ProtoMessage() {}

func (x *CreateTestReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestReminderRequest.ProtoReflect.Descriptor instead.
func (*CreateTestReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{23}
}

func (x *CreateTestReminderRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateTestReminderRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTestReminderRequest) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *CreateTestReminderRequest) GetSendEmail() bool {
	if x != nil {
		return x.SendEmail
	}
	return false
}

type CreateTestReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Reminder      *Reminder              `protobuf:"bytes,2,opt,name=reminder,proto3" json:"reminder,omitempty"`
	Event         *Event                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	EmailSent     bool                   `protobuf:"varint,4,opt,name=email_sent,json=emailSent,proto3" json:"email_sent,omitempty"`
	EmailError    string                 `protobuf:"bytes,5,opt,name=email_error,json=emailError,proto3" json:"email_error,omitempty"` // 可空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTestReminderResponse) Reset() {
	*x = CreateTestReminderResponse{}
	mi := &file_reminder_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTestReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestReminderResponse) ProtoMessage() {}

func (x *CreateTestReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestReminderResponse.ProtoReflect.Descriptor instead.
func (*CreateTestReminderResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{24}
}

func (x *CreateTestReminderResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateTestReminderResponse) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

func (x *CreateTestReminderResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CreateTestReminderResponse) GetEmailSent() bool {
	if x != nil {
		return x.EmailSent
	}
	return false
}

func (x *CreateTestReminderResponse) GetEmailError() string {
	if x != nil {
		return x.EmailError
	}
	return ""
}

var File_reminder_proto protoreflect.FileDescriptor

const file_reminder_proto_rawDesc = "" +
	"\n" +
	"\x0ereminder.proto\x12\x0etodoing.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\x1a\vevent.proto\"\xca\x04\n" +
	"\bReminder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12!\n" +
	"\fadvance_days\x18\x04 \x01(\x05R\vadvanceDays\x12%\n" +
	"\x0ereminder_times\x18\x05 \x03(\tR\rreminderTimes\x12A\n" +
	"\x0eabsolute_times\x18\x06 \x03(\v2\x1a.google.protobuf.TimestampR\rabsoluteTimes\x12A\n" +
	"\rreminder_type\x18\a \x01(\x0e2\x1c.todoing.api.v1.ReminderTypeR\freminderType\x12%\n" +
	"\x0ecustom_message\x18\b \x01(\tR\rcustomMessage\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x127\n" +
	"\tlast_sent\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\blastSent\x127\n" +
	"\tnext_send\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bnextSend\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"v\n" +
	"\x11ReminderWithEvent\x124\n" +
	"\breminder\x18\x01 \x01(\v2\x18.todoing.api.v1.ReminderR\breminder\x12+\n" +
	"\x05event\x18\x02 \x01(\v2\x15.todoing.api.v1.EventR\x05event\"\xa9\x02\n" +
	"\x15CreateReminderRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12!\n" +
	"\fadvance_days\x18\x02 \x01(\x05R\vadvanceDays\x12%\n" +
	"\x0ereminder_times\x18\x03 \x03(\tR\rreminderTimes\x12A\n" +
	"\x0eabsolute_times\x18\x04 \x03(\v2\x1a.google.protobuf.TimestampR\rabsoluteTimes\x12A\n" +
	"\rreminder_type\x18\x05 \x01(\x0e2\x1c.todoing.api.v1.ReminderTypeR\freminderType\x12%\n" +
	"\x0ecustom_message\x18\x06 \x01(\tR\rcustomMessage\"\x84\x01\n" +
	"\x16CreateReminderResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x124\n" +
	"\breminder\x18\x02 \x01(\v2\x18.todoing.api.v1.ReminderR\breminder\"$\n" +
	"\x12GetReminderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8a\x01\n" +
	"\x13GetReminderResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12=\n" +
	"\breminder\x18\x02 \x01(\v2!.todoing.api.v1.ReminderWithEventR\breminder\"\xbb\x02\n" +
	"\x15UpdateReminderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fadvance_days\x18\x02 \x01(\x05R\vadvanceDays\x12%\n" +
	"\x0ereminder_times\x18\x03 \x03(\tR\rreminderTimes\x12A\n" +
	"\x0eabsolute_times\x18\x04 \x03(\v2\x1a.google.protobuf.TimestampR\rabsoluteTimes\x12A\n" +
	"\rreminder_type\x18\x05 \x01(\x0e2\x1c.todoing.api.v1.ReminderTypeR\freminderType\x12%\n" +
	"\x0ecustom_message\x18\x06 \x01(\tR\rcustomMessage\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"\x84\x01\n" +
	"\x16UpdateReminderResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x124\n" +
	"\breminder\x18\x02 \x01(\v2\x18.todoing.api.v1.ReminderR\breminder\"'\n" +
	"\x15DeleteReminderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"z\n" +
	"\x14ListRemindersRequest\x12A\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2!.todoing.api.v1.PaginationRequestR\n" +
	"pagination\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\"\xd2\x01\n" +
	"\x15ListRemindersResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12?\n" +
	"\treminders\x18\x02 \x03(\v2!.todoing.api.v1.ReminderWithEventR\treminders\x12B\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\".todoing.api.v1.PaginationResponseR\n" +
	"pagination\"S\n" +
	"\x1aListSimpleRemindersRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xa1\x01\n" +
	"\x1bListSimpleRemindersResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x126\n" +
	"\treminders\x18\x02 \x03(\v2\x18.todoing.api.v1.ReminderR\treminders\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\x92\x02\n" +
	"\x10UpcomingReminder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vevent_title\x18\x02 \x01(\tR\n" +
	"eventTitle\x129\n" +
	"\n" +
	"event_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\teventDate\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1b\n" +
	"\tdays_left\x18\x05 \x01(\x05R\bdaysLeft\x12\x1e\n" +
	"\n" +
	"importance\x18\x06 \x01(\x05R\n" +
	"importance\x12;\n" +
	"\vreminder_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reminderAt\"3\n" +
	"\x1bGetUpcomingRemindersRequest\x12\x14\n" +
	"\x05hours\x18\x01 \x01(\x05R\x05hours\"\xaa\x01\n" +
	"\x1cGetUpcomingRemindersResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12>\n" +
	"\treminders\x18\x02 \x03(\v2 .todoing.api.v1.UpcomingReminderR\treminders\x12\x14\n" +
	"\x05hours\x18\x03 \x01(\x05R\x05hours\"}\n" +
	"\x16PreviewReminderRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12!\n" +
	"\fadvance_days\x18\x02 \x01(\x05R\vadvanceDays\x12%\n" +
	"\x0ereminder_times\x18\x03 \x03(\tR\rreminderTimes\"l\n" +
	"\x13PreviewReminderItem\x12;\n" +
	"\vreminder_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reminderAt\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x01\n" +
	"\x17PreviewReminderResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12?\n" +
	"\bschedule\x18\x02 \x03(\v2#.todoing.api.v1.PreviewReminderItemR\bschedule\"N\n" +
	"\x15SnoozeReminderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0esnooze_minutes\x18\x02 \x01(\x05R\rsnoozeMinutes\"u\n" +
	"\x16SnoozeReminderResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12%\n" +
	"\x0esnooze_minutes\x18\x02 \x01(\x05R\rsnoozeMinutes\"-\n" +
	"\x1bToggleReminderActiveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"q\n" +
	"\x1cToggleReminderActiveResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\"\x94\x01\n" +
	"\x19CreateTestReminderRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rdelay_seconds\x18\x03 \x01(\x05R\fdelaySeconds\x12\x1d\n" +
	"\n" +
	"send_email\x18\x04 \x01(\bR\tsendEmail\"\xf5\x01\n" +
	"\x1aCreateTestReminderResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x124\n" +
	"\breminder\x18\x02 \x01(\v2\x18.todoing.api.v1.ReminderR\breminder\x12+\n" +
	"\x05event\x18\x03 \x01(\v2\x15.todoing.api.v1.EventR\x05event\x12\x1d\n" +
	"\n" +
	"email_sent\x18\x04 \x01(\bR\temailSent\x12\x1f\n" +
	"\vemail_error\x18\x05 \x01(\tR\n" +
	"emailError*u\n" +
	"\fReminderType\x12\x1d\n" +
	"\x19REMINDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11REMINDER_TYPE_APP\x10\x01\x12\x17\n" +
	"\x13REMINDER_TYPE_EMAIL\x10\x02\x12\x16\n" +
	"\x12REMINDER_TYPE_BOTH\x10\x032\xe4\b\n" +
	"\x0fReminderService\x12_\n" +
	"\x0eCreateReminder\x12%.todoing.api.v1.CreateReminderRequest\x1a&.todoing.api.v1.CreateReminderResponse\x12V\n" +
	"\vGetReminder\x12\".todoing.api.v1.GetReminderRequest\x1a#.todoing.api.v1.GetReminderResponse\x12_\n" +
	"\x0eUpdateReminder\x12%.todoing.api.v1.UpdateReminderRequest\x1a&.todoing.api.v1.UpdateReminderResponse\x12Q\n" +
	"\x0eDeleteReminder\x12%.todoing.api.v1.DeleteReminderRequest\x1a\x18.todoing.api.v1.Response\x12\\\n" +
	"\rListReminders\x12$.todoing.api.v1.ListRemindersRequest\x1a%.todoing.api.v1.ListRemindersResponse\x12n\n" +
	"\x13ListSimpleReminders\x12*.todoing.api.v1.ListSimpleRemindersRequest\x1a+.todoing.api.v1.ListSimpleRemindersResponse\x12q\n" +
	"\x14GetUpcomingReminders\x12+.todoing.api.v1.GetUpcomingRemindersRequest\x1a,.todoing.api.v1.GetUpcomingRemindersResponse\x12b\n" +
	"\x0fPreviewReminder\x12&.todoing.api.v1.PreviewReminderRequest\x1a'.todoing.api.v1.PreviewReminderResponse\x12_\n" +
	"\x0eSnoozeReminder\x12%.todoing.api.v1.SnoozeReminderRequest\x1a&.todoing.api.v1.SnoozeReminderResponse\x12q\n" +
	"\x14ToggleReminderActive\x12+.todoing.api.v1.ToggleReminderActiveRequest\x1a,.todoing.api.v1.ToggleReminderActiveResponse\x12k\n" +
	"\x12CreateTestReminder\x12).todoing.api.v1.CreateTestReminderRequest\x1a*.todoing.api.v1.CreateTestReminderResponseB5Z3github.com/axfinn/todoIngPlus/backend-go/pkg/api/v1b\x06proto3"

var (
	file_reminder_proto_rawDescOnce sync.Once
	file_reminder_proto_rawDescData []byte
)

func file_reminder_proto_rawDescGZIP() []byte {
	file_reminder_proto_rawDescOnce.Do(func() {
		file_reminder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reminder_proto_rawDesc), len(file_reminder_proto_rawDesc)))
	})
	return file_reminder_proto_rawDescData
}

var file_reminder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reminder_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_reminder_proto_goTypes = []any{
	(ReminderType)(0),                    // 0: todoing.api.v1.ReminderType
	(*Reminder)(nil),                     // 1: todoing.api.v1.Reminder
	(*ReminderWithEvent)(nil),            // 2: todoing.api.v1.ReminderWithEvent
	(*CreateReminderRequest)(nil),        // 3: todoing.api.v1.CreateReminderRequest
	(*CreateReminderResponse)(nil),       // 4: todoing.api.v1.CreateReminderResponse
	(*GetReminderRequest)(nil),           // 5: todoing.api.v1.GetReminderRequest
	(*GetReminderResponse)(nil),          // 6: todoing.api.v1.GetReminderResponse
	(*UpdateReminderRequest)(nil),        // 7: todoing.api.v1.UpdateReminderRequest
	(*UpdateReminderResponse)(nil),       // 8: todoing.api.v1.UpdateReminderResponse
	(*DeleteReminderRequest)(nil),        // 9: todoing.api.v1.DeleteReminderRequest
	(*ListRemindersRequest)(nil),         // 10: todoing.api.v1.ListRemindersRequest
	(*ListRemindersResponse)(nil),        // 11: todoing.api.v1.ListRemindersResponse
	(*ListSimpleRemindersRequest)(nil),   // 12: todoing.api.v1.ListSimpleRemindersRequest
	(*ListSimpleRemindersResponse)(nil),  // 13: todoing.api.v1.ListSimpleRemindersResponse
	(*UpcomingReminder)(nil),             // 14: todoing.api.v1.UpcomingReminder
	(*GetUpcomingRemindersRequest)(nil),  // 15: todoing.api.v1.GetUpcomingRemindersRequest
	(*GetUpcomingRemindersResponse)(nil), // 16: todoing.api.v1.GetUpcomingRemindersResponse
	(*PreviewReminderRequest)(nil),       // 17: todoing.api.v1.PreviewReminderRequest
	(*PreviewReminderItem)(nil),          // 18: todoing.api.v1.PreviewReminderItem
	(*PreviewReminderResponse)(nil),      // 19: todoing.api.v1.PreviewReminderResponse
	(*SnoozeReminderRequest)(nil),        // 20: todoing.api.v1.SnoozeReminderRequest
	(*SnoozeReminderResponse)(nil),       // 21: todoing.api.v1.SnoozeReminderResponse
	(*ToggleReminderActiveRequest)(nil),  // 22: todoing.api.v1.ToggleReminderActiveRequest
	(*ToggleReminderActiveResponse)(nil), // 23: todoing.api.v1.ToggleReminderActiveResponse
	(*CreateTestReminderRequest)(nil),    // 24: todoing.api.v1.CreateTestReminderRequest
	(*CreateTestReminderResponse)(nil),   // 25: todoing.api.v1.CreateTestReminderResponse
	(*timestamppb.Timestamp)(nil),        // 26: google.protobuf.Timestamp
	(*Event)(nil),                        // 27: todoing.api.v1.Event
	(*Response)(nil),                     // 28: todoing.api.v1.Response
	(*PaginationRequest)(nil),            // 29: todoing.api.v1.PaginationRequest
	(*PaginationResponse)(nil),           // 30: todoing.api.v1.PaginationResponse
}
var file_reminder_proto_depIdxs = []int32{
	26, // 0: todoing.api.v1.Reminder.absolute_times:type_name -> google.protobuf.Timestamp
	0,  // 1: todoing.api.v1.Reminder.reminder_type:type_name -> todoing.api.v1.ReminderType
	26, // 2: todoing.api.v1.Reminder.last_sent:type_name -> google.protobuf.Timestamp
	26, // 3: todoing.api.v1.Reminder.next_send:type_name -> google.protobuf.Timestamp
	26, // 4: todoing.api.v1.Reminder.created_at:type_name -> google.protobuf.Timestamp
	26, // 5: todoing.api.v1.Reminder.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: todoing.api.v1.ReminderWithEvent.reminder:type_name -> todoing.api.v1.Reminder
	27, // 7: todoing.api.v1.ReminderWithEvent.event:type_name -> todoing.api.v1.Event
	26, // 8: todoing.api.v1.CreateReminderRequest.absolute_times:type_name -> google.protobuf.Timestamp
	0,  // 9: todoing.api.v1.CreateReminderRequest.reminder_type:type_name -> todoing.api.v1.ReminderType
	28, // 10: todoing.api.v1.CreateReminderResponse.response:type_name -> todoing.api.v1.Response
	1,  // 11: todoing.api.v1.CreateReminderResponse.reminder:type_name -> todoing.api.v1.Reminder
	28, // 12: todoing.api.v1.GetReminderResponse.response:type_name -> todoing.api.v1.Response
	2,  // 13: todoing.api.v1.GetReminderResponse.reminder:type_name -> todoing.api.v1.ReminderWithEvent
	26, // 14: todoing.api.v1.UpdateReminderRequest.absolute_times:type_name -> google.protobuf.Timestamp
	0,  // 15: todoing.api.v1.UpdateReminderRequest.reminder_type:type_name -> todoing.api.v1.ReminderType
	28, // 16: todoing.api.v1.UpdateReminderResponse.response:type_name -> todoing.api.v1.Response
	1,  // 17: todoing.api.v1.UpdateReminderResponse.reminder:type_name -> todoing.api.v1.Reminder
	29, // 18: todoing.api.v1.ListRemindersRequest.pagination:type_name -> todoing.api.v1.PaginationRequest
	28, // 19: todoing.api.v1.ListRemindersResponse.response:type_name -> todoing.api.v1.Response
	2,  // 20: todoing.api.v1.ListRemindersResponse.reminders:type_name -> todoing.api.v1.ReminderWithEvent
	30, // 21: todoing.api.v1.ListRemindersResponse.pagination:type_name -> todoing.api.v1.PaginationResponse
	28, // 22: todoing.api.v1.ListSimpleRemindersResponse.response:type_name -> todoing.api.v1.Response
	1,  // 23: todoing.api.v1.ListSimpleRemindersResponse.reminders:type_name -> todoing.api.v1.Reminder
	26, // 24: todoing.api.v1.UpcomingReminder.event_date:type_name -> google.protobuf.Timestamp
	26, // 25: todoing.api.v1.UpcomingReminder.reminder_at:type_name -> google.protobuf.Timestamp
	28, // 26: todoing.api.v1.GetUpcomingRemindersResponse.response:type_name -> todoing.api.v1.Response
	14, // 27: todoing.api.v1.GetUpcomingRemindersResponse.reminders:type_name -> todoing.api.v1.UpcomingReminder
	26, // 28: todoing.api.v1.PreviewReminderItem.reminder_at:type_name -> google.protobuf.Timestamp
	28, // 29: todoing.api.v1.PreviewReminderResponse.response:type_name -> todoing.api.v1.Response
	18, // 30: todoing.api.v1.PreviewReminderResponse.schedule:type_name -> todoing.api.v1.PreviewReminderItem
	28, // 31: todoing.api.v1.SnoozeReminderResponse.response:type_name -> todoing.api.v1.Response
	28, // 32: todoing.api.v1.ToggleReminderActiveResponse.response:type_name -> todoing.api.v1.Response
	28, // 33: todoing.api.v1.CreateTestReminderResponse.response:type_name -> todoing.api.v1.Response
	1,  // 34: todoing.api.v1.CreateTestReminderResponse.reminder:type_name -> todoing.api.v1.Reminder
	27, // 35: todoing.api.v1.CreateTestReminderResponse.event:type_name -> todoing.api.v1.Event
	3,  // 36: todoing.api.v1.ReminderService.CreateReminder:input_type -> todoing.api.v1.CreateReminderRequest
	5,  // 37: todoing.api.v1.ReminderService.GetReminder:input_type -> todoing.api.v1.GetReminderRequest
	7,  // 38: todoing.api.v1.ReminderService.UpdateReminder:input_type -> todoing.api.v1.UpdateReminderRequest
	9,  // 39: todoing.api.v1.ReminderService.DeleteReminder:input_type -> todoing.api.v1.DeleteReminderRequest
	10, // 40: todoing.api.v1.ReminderService.ListReminders:input_type -> todoing.api.v1.ListRemindersRequest
	12, // 41: todoing.api.v1.ReminderService.ListSimpleReminders:input_type -> todoing.api.v1.ListSimpleRemindersRequest
	15, // 42: todoing.api.v1.ReminderService.GetUpcomingReminders:input_type -> todoing.api.v1.GetUpcomingRemindersRequest
	17, // 43: todoing.api.v1.ReminderService.PreviewReminder:input_type -> todoing.api.v1.PreviewReminderRequest
	20, // 44: todoing.api.v1.ReminderService.SnoozeReminder:input_type -> todoing.api.v1.SnoozeReminderRequest
	22, // 45: todoing.api.v1.ReminderService.ToggleReminderActive:input_type -> todoing.api.v1.ToggleReminderActiveRequest
	24, // 46: todoing.api.v1.ReminderService.CreateTestReminder:input_type -> todoing.api.v1.CreateTestReminderRequest
	4,  // 47: todoing.api.v1.ReminderService.CreateReminder:output_type -> todoing.api.v1.CreateReminderResponse
	6,  // 48: todoing.api.v1.ReminderService.GetReminder:output_type -> todoing.api.v1.GetReminderResponse
	8,  // 49: todoing.api.v1.ReminderService.UpdateReminder:output_type -> todoing.api.v1.UpdateReminderResponse
	28, // 50: todoing.api.v1.ReminderService.DeleteReminder:output_type -> todoing.api.v1.Response
	11, // 51: todoing.api.v1.ReminderService.ListReminders:output_type -> todoing.api.v1.ListRemindersResponse
	13, // 52: todoing.api.v1.ReminderService.ListSimpleReminders:output_type -> todoing.api.v1.ListSimpleRemindersResponse
	16, // 53: todoing.api.v1.ReminderService.GetUpcomingReminders:output_type -> todoing.api.v1.GetUpcomingRemindersResponse
	19, // 54: todoing.api.v1.ReminderService.PreviewReminder:output_type -> todoing.api.v1.PreviewReminderResponse
	21, // 55: todoing.api.v1.ReminderService.SnoozeReminder:output_type -> todoing.api.v1.SnoozeReminderResponse
	23, // 56: todoing.api.v1.ReminderService.ToggleReminderActive:output_type -> todoing.api.v1.ToggleReminderActiveResponse
	25, // 57: todoing.api.v1.ReminderService.CreateTestReminder:output_type -> todoing.api.v1.CreateTestReminderResponse
	47, // [47:58] is the sub-list for method output_type
	36, // [36:47] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_reminder_proto_init() }
func file_reminder_proto_init() {
	if File_reminder_proto != nil {
		return
	}
	file_common_proto_init()
	file_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reminder_proto_rawDesc), len(file_reminder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reminder_proto_goTypes,
		DependencyIndexes: file_reminder_proto_depIdxs,
		EnumInfos:         file_reminder_proto_enumTypes,
		MessageInfos:      file_reminder_proto_msgTypes,
	}.Build()
	File_reminder_proto = out.File
	file_reminder_proto_goTypes = nil
	file_reminder_proto_depIdxs = nil
}
