// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.5
// source: report.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 报表类型枚举
type ReportType int32

const (
	ReportType_REPORT_TYPE_UNSPECIFIED ReportType = 0
	ReportType_REPORT_TYPE_DAILY       ReportType = 1
	ReportType_REPORT_TYPE_WEEKLY      ReportType = 2
	ReportType_REPORT_TYPE_MONTHLY     ReportType = 3
)

// Enum value maps for ReportType.
var (
	ReportType_name = map[int32]string{
		0: "REPORT_TYPE_UNSPECIFIED",
		1: "REPORT_TYPE_DAILY",
		2: "REPORT_TYPE_WEEKLY",
		3: "REPORT_TYPE_MONTHLY",
	}
	ReportType_value = map[string]int32{
		"REPORT_TYPE_UNSPECIFIED": 0,
		"REPORT_TYPE_DAILY":       1,
		"REPORT_TYPE_WEEKLY":      2,
		"REPORT_TYPE_MONTHLY":     3,
	}
)

func (x ReportType) Enum() *ReportType {
	p := new(ReportType)
	*p = x
	return p
}

func (x ReportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportType) Descriptor() protoreflect.EnumDescriptor {
	return file_report_proto_enumTypes[0].Descriptor()
}

func (ReportType) Type() protoreflect.EnumType {
	return &file_report_proto_enumTypes[0]
}

func (x ReportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportType.Descriptor instead.
func (ReportType) EnumDescriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

// 报表模型
type Report struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type            ReportType             `protobuf:"varint,3,opt,name=type,proto3,enum=todoing.api.v1.ReportType" json:"type,omitempty"`
	StartDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 可用 created_at 替代旧结构
	EndDate         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 可用 updated_at 替代
	UserId          string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Tasks           []*Task                `protobuf:"bytes,8,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Stats           *ReportStats           `protobuf:"bytes,9,opt,name=stats,proto3" json:"stats,omitempty"`
	Period          string                 `protobuf:"bytes,10,opt,name=period,proto3" json:"period,omitempty"`                                          // 新增 对齐后端 Period
	Content         string                 `protobuf:"bytes,11,opt,name=content,proto3" json:"content,omitempty"`                                        // 新增 原始内容
	PolishedContent string                 `protobuf:"bytes,12,opt,name=polished_content,json=polishedContent,proto3" json:"polished_content,omitempty"` // 新增 精炼内容
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

func (x *Report) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Report) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Report) GetType() ReportType {
	if x != nil {
		return x.Type
	}
	return ReportType_REPORT_TYPE_UNSPECIFIED
}

func (x *Report) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Report) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Report) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Report) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Report) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Report) GetStats() *ReportStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Report) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Report) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Report) GetPolishedContent() string {
	if x != nil {
		return x.PolishedContent
	}
	return ""
}

// 报表统计信息
type ReportStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalTasks      int32                  `protobuf:"varint,1,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CompletedTasks  int32                  `protobuf:"varint,2,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	PendingTasks    int32                  `protobuf:"varint,3,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	InProgressTasks int32                  `protobuf:"varint,4,opt,name=in_progress_tasks,json=inProgressTasks,proto3" json:"in_progress_tasks,omitempty"`
	CompletionRate  float64                `protobuf:"fixed64,5,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	OverdueTasks    int32                  `protobuf:"varint,6,opt,name=overdue_tasks,json=overdueTasks,proto3" json:"overdue_tasks,omitempty"` // 新增 与后端 Statistics.OverdueTasks
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportStats) Reset() {
	*x = ReportStats{}
	mi := &file_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStats) ProtoMessage() {}

func (x *ReportStats) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStats.ProtoReflect.Descriptor instead.
func (*ReportStats) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{1}
}

func (x *ReportStats) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *ReportStats) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *ReportStats) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

func (x *ReportStats) GetInProgressTasks() int32 {
	if x != nil {
		return x.InProgressTasks
	}
	return 0
}

func (x *ReportStats) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *ReportStats) GetOverdueTasks() int32 {
	if x != nil {
		return x.OverdueTasks
	}
	return 0
}

// 生成报表请求
type GenerateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type          ReportType             `protobuf:"varint,2,opt,name=type,proto3,enum=todoing.api.v1.ReportType" json:"type,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest) Reset() {
	*x = GenerateReportRequest{}
	mi := &file_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest) ProtoMessage() {}

func (x *GenerateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateReportRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GenerateReportRequest) GetType() ReportType {
	if x != nil {
		return x.Type
	}
	return ReportType_REPORT_TYPE_UNSPECIFIED
}

func (x *GenerateReportRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GenerateReportRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

// 生成报表响应
type GenerateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Report        *Report                `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportResponse) Reset() {
	*x = GenerateReportResponse{}
	mi := &file_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportResponse) ProtoMessage() {}

func (x *GenerateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateReportResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateReportResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GenerateReportResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

// 获取报表列表请求
type GetReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Type          ReportType             `protobuf:"varint,2,opt,name=type,proto3,enum=todoing.api.v1.ReportType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportsRequest) Reset() {
	*x = GetReportsRequest{}
	mi := &file_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportsRequest) ProtoMessage() {}

func (x *GetReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportsRequest.ProtoReflect.Descriptor instead.
func (*GetReportsRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{4}
}

func (x *GetReportsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetReportsRequest) GetType() ReportType {
	if x != nil {
		return x.Type
	}
	return ReportType_REPORT_TYPE_UNSPECIFIED
}

// 获取报表列表响应
type GetReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Reports       []*Report              `protobuf:"bytes,2,rep,name=reports,proto3" json:"reports,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportsResponse) Reset() {
	*x = GetReportsResponse{}
	mi := &file_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportsResponse) ProtoMessage() {}

func (x *GetReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportsResponse.ProtoReflect.Descriptor instead.
func (*GetReportsResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{5}
}

func (x *GetReportsResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetReportsResponse) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *GetReportsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 获取报表请求
type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{6}
}

func (x *GetReportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取报表响应
type GetReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Report        *Report                `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportResponse) Reset() {
	*x = GetReportResponse{}
	mi := &file_report_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportResponse) ProtoMessage() {}

func (x *GetReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportResponse.ProtoReflect.Descriptor instead.
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{7}
}

func (x *GetReportResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetReportResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

// 删除报表请求
type DeleteReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReportRequest) Reset() {
	*x = DeleteReportRequest{}
	mi := &file_report_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReportRequest) ProtoMessage() {}

func (x *DeleteReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReportRequest.ProtoReflect.Descriptor instead.
func (*DeleteReportRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteReportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 导出报表请求
type ExportReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // "csv", "excel", "pdf"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReportRequest) Reset() {
	*x = ExportReportRequest{}
	mi := &file_report_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReportRequest) ProtoMessage() {}

func (x *ExportReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReportRequest.ProtoReflect.Descriptor instead.
func (*ExportReportRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{9}
}

func (x *ExportReportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportReportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// 导出报表响应
type ExportReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReportResponse) Reset() {
	*x = ExportReportResponse{}
	mi := &file_report_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReportResponse) ProtoMessage() {}

func (x *ExportReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReportResponse.ProtoReflect.Descriptor instead.
func (*ExportReportResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{10}
}

func (x *ExportReportResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ExportReportResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExportReportResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExportReportResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_report_proto protoreflect.FileDescriptor

const file_report_proto_rawDesc = "" +
	"\n" +
	"\freport.proto\x12\x0etodoing.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\x1a\n" +
	"task.proto\x1a\vevent.proto\"\xe0\x03\n" +
	"\x06Report\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.todoing.api.v1.ReportTypeR\x04type\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12*\n" +
	"\x05tasks\x18\b \x03(\v2\x14.todoing.api.v1.TaskR\x05tasks\x121\n" +
	"\x05stats\x18\t \x01(\v2\x1b.todoing.api.v1.ReportStatsR\x05stats\x12\x16\n" +
	"\x06period\x18\n" +
	" \x01(\tR\x06period\x12\x18\n" +
	"\acontent\x18\v \x01(\tR\acontent\x12)\n" +
	"\x10polished_content\x18\f \x01(\tR\x0fpolishedContent\"\xf6\x01\n" +
	"\vReportStats\x12\x1f\n" +
	"\vtotal_tasks\x18\x01 \x01(\x05R\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x02 \x01(\x05R\x0ecompletedTasks\x12#\n" +
	"\rpending_tasks\x18\x03 \x01(\x05R\fpendingTasks\x12*\n" +
	"\x11in_progress_tasks\x18\x04 \x01(\x05R\x0finProgressTasks\x12'\n" +
	"\x0fcompletion_rate\x18\x05 \x01(\x01R\x0ecompletionRate\x12#\n" +
	"\roverdue_tasks\x18\x06 \x01(\x05R\foverdueTasks\"\xcf\x01\n" +
	"\x15GenerateReportRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.todoing.api.v1.ReportTypeR\x04type\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"~\n" +
	"\x16GenerateReportResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12.\n" +
	"\x06report\x18\x02 \x01(\v2\x16.todoing.api.v1.ReportR\x06report\"\x86\x01\n" +
	"\x11GetReportsRequest\x12A\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2!.todoing.api.v1.PaginationRequestR\n" +
	"pagination\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.todoing.api.v1.ReportTypeR\x04type\"\xc0\x01\n" +
	"\x12GetReportsResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x120\n" +
	"\areports\x18\x02 \x03(\v2\x16.todoing.api.v1.ReportR\areports\x12B\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\".todoing.api.v1.PaginationResponseR\n" +
	"pagination\"\"\n" +
	"\x10GetReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"y\n" +
	"\x11GetReportResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12.\n" +
	"\x06report\x18\x02 \x01(\v2\x16.todoing.api.v1.ReportR\x06report\"%\n" +
	"\x13DeleteReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x13ExportReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\x9f\x01\n" +
	"\x14ExportReportResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType*q\n" +
	"\n" +
	"ReportType\x12\x1b\n" +
	"\x17REPORT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11REPORT_TYPE_DAILY\x10\x01\x12\x16\n" +
	"\x12REPORT_TYPE_WEEKLY\x10\x02\x12\x17\n" +
	"\x13REPORT_TYPE_MONTHLY\x10\x032\xc1\x03\n" +
	"\rReportService\x12_\n" +
	"\x0eGenerateReport\x12%.todoing.api.v1.GenerateReportRequest\x1a&.todoing.api.v1.GenerateReportResponse\x12S\n" +
	"\n" +
	"GetReports\x12!.todoing.api.v1.GetReportsRequest\x1a\".todoing.api.v1.GetReportsResponse\x12P\n" +
	"\tGetReport\x12 .todoing.api.v1.GetReportRequest\x1a!.todoing.api.v1.GetReportResponse\x12M\n" +
	"\fDeleteReport\x12#.todoing.api.v1.DeleteReportRequest\x1a\x18.todoing.api.v1.Response\x12Y\n" +
	"\fExportReport\x12#.todoing.api.v1.ExportReportRequest\x1a$.todoing.api.v1.ExportReportResponseB5Z3github.com/axfinn/todoIngPlus/backend-go/pkg/api/v1b\x06proto3"

var (
	file_report_proto_rawDescOnce sync.Once
	file_report_proto_rawDescData []byte
)

func file_report_proto_rawDescGZIP() []byte {
	file_report_proto_rawDescOnce.Do(func() {
		file_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)))
	})
	return file_report_proto_rawDescData
}

var file_report_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_report_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_report_proto_goTypes = []any{
	(ReportType)(0),                // 0: todoing.api.v1.ReportType
	(*Report)(nil),                 // 1: todoing.api.v1.Report
	(*ReportStats)(nil),            // 2: todoing.api.v1.ReportStats
	(*GenerateReportRequest)(nil),  // 3: todoing.api.v1.GenerateReportRequest
	(*GenerateReportResponse)(nil), // 4: todoing.api.v1.GenerateReportResponse
	(*GetReportsRequest)(nil),      // 5: todoing.api.v1.GetReportsRequest
	(*GetReportsResponse)(nil),     // 6: todoing.api.v1.GetReportsResponse
	(*GetReportRequest)(nil),       // 7: todoing.api.v1.GetReportRequest
	(*GetReportResponse)(nil),      // 8: todoing.api.v1.GetReportResponse
	(*DeleteReportRequest)(nil),    // 9: todoing.api.v1.DeleteReportRequest
	(*ExportReportRequest)(nil),    // 10: todoing.api.v1.ExportReportRequest
	(*ExportReportResponse)(nil),   // 11: todoing.api.v1.ExportReportResponse
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
	(*Task)(nil),                   // 13: todoing.api.v1.Task
	(*Response)(nil),               // 14: todoing.api.v1.Response
	(*PaginationRequest)(nil),      // 15: todoing.api.v1.PaginationRequest
	(*PaginationResponse)(nil),     // 16: todoing.api.v1.PaginationResponse
}
var file_report_proto_depIdxs = []int32{
	0,  // 0: todoing.api.v1.Report.type:type_name -> todoing.api.v1.ReportType
	12, // 1: todoing.api.v1.Report.start_date:type_name -> google.protobuf.Timestamp
	12, // 2: todoing.api.v1.Report.end_date:type_name -> google.protobuf.Timestamp
	12, // 3: todoing.api.v1.Report.created_at:type_name -> google.protobuf.Timestamp
	13, // 4: todoing.api.v1.Report.tasks:type_name -> todoing.api.v1.Task
	2,  // 5: todoing.api.v1.Report.stats:type_name -> todoing.api.v1.ReportStats
	0,  // 6: todoing.api.v1.GenerateReportRequest.type:type_name -> todoing.api.v1.ReportType
	12, // 7: todoing.api.v1.GenerateReportRequest.start_date:type_name -> google.protobuf.Timestamp
	12, // 8: todoing.api.v1.GenerateReportRequest.end_date:type_name -> google.protobuf.Timestamp
	14, // 9: todoing.api.v1.GenerateReportResponse.response:type_name -> todoing.api.v1.Response
	1,  // 10: todoing.api.v1.GenerateReportResponse.report:type_name -> todoing.api.v1.Report
	15, // 11: todoing.api.v1.GetReportsRequest.pagination:type_name -> todoing.api.v1.PaginationRequest
	0,  // 12: todoing.api.v1.GetReportsRequest.type:type_name -> todoing.api.v1.ReportType
	14, // 13: todoing.api.v1.GetReportsResponse.response:type_name -> todoing.api.v1.Response
	1,  // 14: todoing.api.v1.GetReportsResponse.reports:type_name -> todoing.api.v1.Report
	16, // 15: todoing.api.v1.GetReportsResponse.pagination:type_name -> todoing.api.v1.PaginationResponse
	14, // 16: todoing.api.v1.GetReportResponse.response:type_name -> todoing.api.v1.Response
	1,  // 17: todoing.api.v1.GetReportResponse.report:type_name -> todoing.api.v1.Report
	14, // 18: todoing.api.v1.ExportReportResponse.response:type_name -> todoing.api.v1.Response
	3,  // 19: todoing.api.v1.ReportService.GenerateReport:input_type -> todoing.api.v1.GenerateReportRequest
	5,  // 20: todoing.api.v1.ReportService.GetReports:input_type -> todoing.api.v1.GetReportsRequest
	7,  // 21: todoing.api.v1.ReportService.GetReport:input_type -> todoing.api.v1.GetReportRequest
	9,  // 22: todoing.api.v1.ReportService.DeleteReport:input_type -> todoing.api.v1.DeleteReportRequest
	10, // 23: todoing.api.v1.ReportService.ExportReport:input_type -> todoing.api.v1.ExportReportRequest
	4,  // 24: todoing.api.v1.ReportService.GenerateReport:output_type -> todoing.api.v1.GenerateReportResponse
	6,  // 25: todoing.api.v1.ReportService.GetReports:output_type -> todoing.api.v1.GetReportsResponse
	8,  // 26: todoing.api.v1.ReportService.GetReport:output_type -> todoing.api.v1.GetReportResponse
	14, // 27: todoing.api.v1.ReportService.DeleteReport:output_type -> todoing.api.v1.Response
	11, // 28: todoing.api.v1.ReportService.ExportReport:output_type -> todoing.api.v1.ExportReportResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_report_proto_init() }
func file_report_proto_init() {
	if File_report_proto != nil {
		return
	}
	file_common_proto_init()
	file_task_proto_init()
	file_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_proto_goTypes,
		DependencyIndexes: file_report_proto_depIdxs,
		EnumInfos:         file_report_proto_enumTypes,
		MessageInfos:      file_report_proto_msgTypes,
	}.Build()
	File_report_proto = out.File
	file_report_proto_goTypes = nil
	file_report_proto_depIdxs = nil
}
