// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.5
// source: task.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务状态枚举
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_TODO        TaskStatus = 1
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 2
	TaskStatus_TASK_STATUS_DONE        TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_TODO",
		2: "TASK_STATUS_IN_PROGRESS",
		3: "TASK_STATUS_DONE",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_TODO":        1,
		"TASK_STATUS_IN_PROGRESS": 2,
		"TASK_STATUS_DONE":        3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

// 任务优先级枚举
type TaskPriority int32

const (
	TaskPriority_TASK_PRIORITY_UNSPECIFIED TaskPriority = 0
	TaskPriority_TASK_PRIORITY_LOW         TaskPriority = 1
	TaskPriority_TASK_PRIORITY_MEDIUM      TaskPriority = 2
	TaskPriority_TASK_PRIORITY_HIGH        TaskPriority = 3
)

// Enum value maps for TaskPriority.
var (
	TaskPriority_name = map[int32]string{
		0: "TASK_PRIORITY_UNSPECIFIED",
		1: "TASK_PRIORITY_LOW",
		2: "TASK_PRIORITY_MEDIUM",
		3: "TASK_PRIORITY_HIGH",
	}
	TaskPriority_value = map[string]int32{
		"TASK_PRIORITY_UNSPECIFIED": 0,
		"TASK_PRIORITY_LOW":         1,
		"TASK_PRIORITY_MEDIUM":      2,
		"TASK_PRIORITY_HIGH":        3,
	}
)

func (x TaskPriority) Enum() *TaskPriority {
	p := new(TaskPriority)
	*p = x
	return p
}

func (x TaskPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[1].Descriptor()
}

func (TaskPriority) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[1]
}

func (x TaskPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPriority.Descriptor instead.
func (TaskPriority) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

// 任务评论
type TaskComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskComment) Reset() {
	*x = TaskComment{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskComment) ProtoMessage() {}

func (x *TaskComment) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskComment.ProtoReflect.Descriptor instead.
func (*TaskComment) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskComment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TaskComment) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *TaskComment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 任务模型
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=todoing.api.v1.TaskStatus" json:"status,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,5,opt,name=priority,proto3,enum=todoing.api.v1.TaskPriority" json:"priority,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"` // deprecated: 旧字段，对应后端 deadline，保留兼容
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ScheduledDate *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=scheduled_date,json=scheduledDate,proto3" json:"scheduled_date,omitempty"` // scheduledDate
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=deadline,proto3" json:"deadline,omitempty"`                                // 真正截止日期
	Assignee      string                 `protobuf:"bytes,12,opt,name=assignee,proto3" json:"assignee,omitempty"`                                // 新增: 与后端 Assignee 对齐（可能为空）
	Comments      []*TaskComment         `protobuf:"bytes,13,rep,name=comments,proto3" json:"comments,omitempty"`                                // 新增: 评论列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *Task) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Task) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Task) GetScheduledDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledDate
	}
	return nil
}

func (x *Task) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Task) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *Task) GetComments() []*TaskComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// 创建任务请求
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=todoing.api.v1.TaskStatus" json:"status,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,4,opt,name=priority,proto3,enum=todoing.api.v1.TaskPriority" json:"priority,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"` // 使用统一字段
	ScheduledDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=scheduled_date,json=scheduledDate,proto3" json:"scheduled_date,omitempty"`
	Assignee      string                 `protobuf:"bytes,7,opt,name=assignee,proto3" json:"assignee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *CreateTaskRequest) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *CreateTaskRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *CreateTaskRequest) GetScheduledDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledDate
	}
	return nil
}

func (x *CreateTaskRequest) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

// 创建任务响应
type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// 获取任务列表请求
type GetTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=todoing.api.v1.TaskStatus" json:"status,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,3,opt,name=priority,proto3,enum=todoing.api.v1.TaskPriority" json:"priority,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,4,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"` // 预留
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *GetTasksRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *GetTasksRequest) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *GetTasksRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

// 获取任务列表响应
type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *GetTasksResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *GetTasksResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 获取任务请求
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取任务响应
type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaskResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// 更新任务请求
type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=todoing.api.v1.TaskStatus" json:"status,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,5,opt,name=priority,proto3,enum=todoing.api.v1.TaskPriority" json:"priority,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	ScheduledDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=scheduled_date,json=scheduledDate,proto3" json:"scheduled_date,omitempty"`
	Assignee      string                 `protobuf:"bytes,8,opt,name=assignee,proto3" json:"assignee,omitempty"`
	Comments      []*TaskComment         `protobuf:"bytes,9,rep,name=comments,proto3" json:"comments,omitempty"` // 全量替换
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *UpdateTaskRequest) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *UpdateTaskRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *UpdateTaskRequest) GetScheduledDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledDate
	}
	return nil
}

func (x *UpdateTaskRequest) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *UpdateTaskRequest) GetComments() []*TaskComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// 更新任务响应
type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTaskResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *UpdateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// 删除任务请求
type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 优先任务 (Dashboard, Unified 使用)
type PriorityTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	PriorityScore float64                `protobuf:"fixed64,2,opt,name=priority_score,json=priorityScore,proto3" json:"priority_score,omitempty"`
	DaysLeft      int32                  `protobuf:"varint,3,opt,name=days_left,json=daysLeft,proto3" json:"days_left,omitempty"`
	IsUrgent      bool                   `protobuf:"varint,4,opt,name=is_urgent,json=isUrgent,proto3" json:"is_urgent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorityTask) Reset() {
	*x = PriorityTask{}
	mi := &file_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityTask) ProtoMessage() {}

func (x *PriorityTask) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityTask.ProtoReflect.Descriptor instead.
func (*PriorityTask) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{11}
}

func (x *PriorityTask) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *PriorityTask) GetPriorityScore() float64 {
	if x != nil {
		return x.PriorityScore
	}
	return 0
}

func (x *PriorityTask) GetDaysLeft() int32 {
	if x != nil {
		return x.DaysLeft
	}
	return 0
}

func (x *PriorityTask) GetIsUrgent() bool {
	if x != nil {
		return x.IsUrgent
	}
	return false
}

// 任务排序配置
type TaskSortConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PriorityDays    int32                  `protobuf:"varint,2,opt,name=priority_days,json=priorityDays,proto3" json:"priority_days,omitempty"`
	MaxDisplayCount int32                  `protobuf:"varint,3,opt,name=max_display_count,json=maxDisplayCount,proto3" json:"max_display_count,omitempty"`
	WeightUrgent    float64                `protobuf:"fixed64,4,opt,name=weight_urgent,json=weightUrgent,proto3" json:"weight_urgent,omitempty"`
	WeightImportant float64                `protobuf:"fixed64,5,opt,name=weight_important,json=weightImportant,proto3" json:"weight_important,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskSortConfig) Reset() {
	*x = TaskSortConfig{}
	mi := &file_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSortConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSortConfig) ProtoMessage() {}

func (x *TaskSortConfig) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSortConfig.ProtoReflect.Descriptor instead.
func (*TaskSortConfig) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{12}
}

func (x *TaskSortConfig) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TaskSortConfig) GetPriorityDays() int32 {
	if x != nil {
		return x.PriorityDays
	}
	return 0
}

func (x *TaskSortConfig) GetMaxDisplayCount() int32 {
	if x != nil {
		return x.MaxDisplayCount
	}
	return 0
}

func (x *TaskSortConfig) GetWeightUrgent() float64 {
	if x != nil {
		return x.WeightUrgent
	}
	return 0
}

func (x *TaskSortConfig) GetWeightImportant() float64 {
	if x != nil {
		return x.WeightImportant
	}
	return 0
}

func (x *TaskSortConfig) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskSortConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 更新任务排序配置
type UpdateTaskSortConfigRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PriorityDays    int32                  `protobuf:"varint,1,opt,name=priority_days,json=priorityDays,proto3" json:"priority_days,omitempty"`
	MaxDisplayCount int32                  `protobuf:"varint,2,opt,name=max_display_count,json=maxDisplayCount,proto3" json:"max_display_count,omitempty"`
	WeightUrgent    float64                `protobuf:"fixed64,3,opt,name=weight_urgent,json=weightUrgent,proto3" json:"weight_urgent,omitempty"`
	WeightImportant float64                `protobuf:"fixed64,4,opt,name=weight_important,json=weightImportant,proto3" json:"weight_important,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTaskSortConfigRequest) Reset() {
	*x = UpdateTaskSortConfigRequest{}
	mi := &file_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskSortConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskSortConfigRequest) ProtoMessage() {}

func (x *UpdateTaskSortConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskSortConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskSortConfigRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTaskSortConfigRequest) GetPriorityDays() int32 {
	if x != nil {
		return x.PriorityDays
	}
	return 0
}

func (x *UpdateTaskSortConfigRequest) GetMaxDisplayCount() int32 {
	if x != nil {
		return x.MaxDisplayCount
	}
	return 0
}

func (x *UpdateTaskSortConfigRequest) GetWeightUrgent() float64 {
	if x != nil {
		return x.WeightUrgent
	}
	return 0
}

func (x *UpdateTaskSortConfigRequest) GetWeightImportant() float64 {
	if x != nil {
		return x.WeightImportant
	}
	return 0
}

type UpdateTaskSortConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Config        *TaskSortConfig        `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskSortConfigResponse) Reset() {
	*x = UpdateTaskSortConfigResponse{}
	mi := &file_task_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskSortConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskSortConfigResponse) ProtoMessage() {}

func (x *UpdateTaskSortConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskSortConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskSortConfigResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateTaskSortConfigResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *UpdateTaskSortConfigResponse) GetConfig() *TaskSortConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetTaskSortConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskSortConfigRequest) Reset() {
	*x = GetTaskSortConfigRequest{}
	mi := &file_task_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskSortConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskSortConfigRequest) ProtoMessage() {}

func (x *GetTaskSortConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskSortConfigRequest.ProtoReflect.Descriptor instead.
func (*GetTaskSortConfigRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{15}
}

type GetTaskSortConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Config        *TaskSortConfig        `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskSortConfigResponse) Reset() {
	*x = GetTaskSortConfigResponse{}
	mi := &file_task_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskSortConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskSortConfigResponse) ProtoMessage() {}

func (x *GetTaskSortConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskSortConfigResponse.ProtoReflect.Descriptor instead.
func (*GetTaskSortConfigResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{16}
}

func (x *GetTaskSortConfigResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetTaskSortConfigResponse) GetConfig() *TaskSortConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x0etodoing.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"{\n" +
	"\vTaskComment\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd2\x04\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.todoing.api.v1.TaskStatusR\x06status\x128\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x1c.todoing.api.v1.TaskPriorityR\bpriority\x125\n" +
	"\bdue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12A\n" +
	"\x0escheduled_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledDate\x126\n" +
	"\bdeadline\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x1a\n" +
	"\bassignee\x18\f \x01(\tR\bassignee\x127\n" +
	"\bcomments\x18\r \x03(\v2\x1b.todoing.api.v1.TaskCommentR\bcomments\"\xd0\x02\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.todoing.api.v1.TaskStatusR\x06status\x128\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x1c.todoing.api.v1.TaskPriorityR\bpriority\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12A\n" +
	"\x0escheduled_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledDate\x12\x1a\n" +
	"\bassignee\x18\a \x01(\tR\bassignee\"t\n" +
	"\x12CreateTaskResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12(\n" +
	"\x04task\x18\x02 \x01(\v2\x14.todoing.api.v1.TaskR\x04task\"\xe3\x01\n" +
	"\x0fGetTasksRequest\x12A\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2!.todoing.api.v1.PaginationRequestR\n" +
	"pagination\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.todoing.api.v1.TaskStatusR\x06status\x128\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x1c.todoing.api.v1.TaskPriorityR\bpriority\x12\x1f\n" +
	"\vactive_only\x18\x04 \x01(\bR\n" +
	"activeOnly\"\xb8\x01\n" +
	"\x10GetTasksResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12*\n" +
	"\x05tasks\x18\x02 \x03(\v2\x14.todoing.api.v1.TaskR\x05tasks\x12B\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\".todoing.api.v1.PaginationResponseR\n" +
	"pagination\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"q\n" +
	"\x0fGetTaskResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12(\n" +
	"\x04task\x18\x02 \x01(\v2\x14.todoing.api.v1.TaskR\x04task\"\x99\x03\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.todoing.api.v1.TaskStatusR\x06status\x128\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x1c.todoing.api.v1.TaskPriorityR\bpriority\x126\n" +
	"\bdeadline\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12A\n" +
	"\x0escheduled_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledDate\x12\x1a\n" +
	"\bassignee\x18\b \x01(\tR\bassignee\x127\n" +
	"\bcomments\x18\t \x03(\v2\x1b.todoing.api.v1.TaskCommentR\bcomments\"t\n" +
	"\x12UpdateTaskResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12(\n" +
	"\x04task\x18\x02 \x01(\v2\x14.todoing.api.v1.TaskR\x04task\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x99\x01\n" +
	"\fPriorityTask\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.todoing.api.v1.TaskR\x04task\x12%\n" +
	"\x0epriority_score\x18\x02 \x01(\x01R\rpriorityScore\x12\x1b\n" +
	"\tdays_left\x18\x03 \x01(\x05R\bdaysLeft\x12\x1b\n" +
	"\tis_urgent\x18\x04 \x01(\bR\bisUrgent\"\xc0\x02\n" +
	"\x0eTaskSortConfig\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rpriority_days\x18\x02 \x01(\x05R\fpriorityDays\x12*\n" +
	"\x11max_display_count\x18\x03 \x01(\x05R\x0fmaxDisplayCount\x12#\n" +
	"\rweight_urgent\x18\x04 \x01(\x01R\fweightUrgent\x12)\n" +
	"\x10weight_important\x18\x05 \x01(\x01R\x0fweightImportant\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbe\x01\n" +
	"\x1bUpdateTaskSortConfigRequest\x12#\n" +
	"\rpriority_days\x18\x01 \x01(\x05R\fpriorityDays\x12*\n" +
	"\x11max_display_count\x18\x02 \x01(\x05R\x0fmaxDisplayCount\x12#\n" +
	"\rweight_urgent\x18\x03 \x01(\x01R\fweightUrgent\x12)\n" +
	"\x10weight_important\x18\x04 \x01(\x01R\x0fweightImportant\"\x8c\x01\n" +
	"\x1cUpdateTaskSortConfigResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x126\n" +
	"\x06config\x18\x02 \x01(\v2\x1e.todoing.api.v1.TaskSortConfigR\x06config\"\x1a\n" +
	"\x18GetTaskSortConfigRequest\"\x89\x01\n" +
	"\x19GetTaskSortConfigResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x126\n" +
	"\x06config\x18\x02 \x01(\v2\x1e.todoing.api.v1.TaskSortConfigR\x06config*r\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TASK_STATUS_TODO\x10\x01\x12\x1b\n" +
	"\x17TASK_STATUS_IN_PROGRESS\x10\x02\x12\x14\n" +
	"\x10TASK_STATUS_DONE\x10\x03*v\n" +
	"\fTaskPriority\x12\x1d\n" +
	"\x19TASK_PRIORITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_PRIORITY_LOW\x10\x01\x12\x18\n" +
	"\x14TASK_PRIORITY_MEDIUM\x10\x02\x12\x16\n" +
	"\x12TASK_PRIORITY_HIGH\x10\x032\xfa\x04\n" +
	"\vTaskService\x12S\n" +
	"\n" +
	"CreateTask\x12!.todoing.api.v1.CreateTaskRequest\x1a\".todoing.api.v1.CreateTaskResponse\x12M\n" +
	"\bGetTasks\x12\x1f.todoing.api.v1.GetTasksRequest\x1a .todoing.api.v1.GetTasksResponse\x12J\n" +
	"\aGetTask\x12\x1e.todoing.api.v1.GetTaskRequest\x1a\x1f.todoing.api.v1.GetTaskResponse\x12S\n" +
	"\n" +
	"UpdateTask\x12!.todoing.api.v1.UpdateTaskRequest\x1a\".todoing.api.v1.UpdateTaskResponse\x12I\n" +
	"\n" +
	"DeleteTask\x12!.todoing.api.v1.DeleteTaskRequest\x1a\x18.todoing.api.v1.Response\x12h\n" +
	"\x11GetTaskSortConfig\x12(.todoing.api.v1.GetTaskSortConfigRequest\x1a).todoing.api.v1.GetTaskSortConfigResponse\x12q\n" +
	"\x14UpdateTaskSortConfig\x12+.todoing.api.v1.UpdateTaskSortConfigRequest\x1a,.todoing.api.v1.UpdateTaskSortConfigResponseB5Z3github.com/axfinn/todoIngPlus/backend-go/pkg/api/v1b\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_task_proto_goTypes = []any{
	(TaskStatus)(0),                      // 0: todoing.api.v1.TaskStatus
	(TaskPriority)(0),                    // 1: todoing.api.v1.TaskPriority
	(*TaskComment)(nil),                  // 2: todoing.api.v1.TaskComment
	(*Task)(nil),                         // 3: todoing.api.v1.Task
	(*CreateTaskRequest)(nil),            // 4: todoing.api.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),           // 5: todoing.api.v1.CreateTaskResponse
	(*GetTasksRequest)(nil),              // 6: todoing.api.v1.GetTasksRequest
	(*GetTasksResponse)(nil),             // 7: todoing.api.v1.GetTasksResponse
	(*GetTaskRequest)(nil),               // 8: todoing.api.v1.GetTaskRequest
	(*GetTaskResponse)(nil),              // 9: todoing.api.v1.GetTaskResponse
	(*UpdateTaskRequest)(nil),            // 10: todoing.api.v1.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),           // 11: todoing.api.v1.UpdateTaskResponse
	(*DeleteTaskRequest)(nil),            // 12: todoing.api.v1.DeleteTaskRequest
	(*PriorityTask)(nil),                 // 13: todoing.api.v1.PriorityTask
	(*TaskSortConfig)(nil),               // 14: todoing.api.v1.TaskSortConfig
	(*UpdateTaskSortConfigRequest)(nil),  // 15: todoing.api.v1.UpdateTaskSortConfigRequest
	(*UpdateTaskSortConfigResponse)(nil), // 16: todoing.api.v1.UpdateTaskSortConfigResponse
	(*GetTaskSortConfigRequest)(nil),     // 17: todoing.api.v1.GetTaskSortConfigRequest
	(*GetTaskSortConfigResponse)(nil),    // 18: todoing.api.v1.GetTaskSortConfigResponse
	(*timestamppb.Timestamp)(nil),        // 19: google.protobuf.Timestamp
	(*Response)(nil),                     // 20: todoing.api.v1.Response
	(*PaginationRequest)(nil),            // 21: todoing.api.v1.PaginationRequest
	(*PaginationResponse)(nil),           // 22: todoing.api.v1.PaginationResponse
}
var file_task_proto_depIdxs = []int32{
	19, // 0: todoing.api.v1.TaskComment.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: todoing.api.v1.Task.status:type_name -> todoing.api.v1.TaskStatus
	1,  // 2: todoing.api.v1.Task.priority:type_name -> todoing.api.v1.TaskPriority
	19, // 3: todoing.api.v1.Task.due_date:type_name -> google.protobuf.Timestamp
	19, // 4: todoing.api.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	19, // 5: todoing.api.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	19, // 6: todoing.api.v1.Task.scheduled_date:type_name -> google.protobuf.Timestamp
	19, // 7: todoing.api.v1.Task.deadline:type_name -> google.protobuf.Timestamp
	2,  // 8: todoing.api.v1.Task.comments:type_name -> todoing.api.v1.TaskComment
	0,  // 9: todoing.api.v1.CreateTaskRequest.status:type_name -> todoing.api.v1.TaskStatus
	1,  // 10: todoing.api.v1.CreateTaskRequest.priority:type_name -> todoing.api.v1.TaskPriority
	19, // 11: todoing.api.v1.CreateTaskRequest.deadline:type_name -> google.protobuf.Timestamp
	19, // 12: todoing.api.v1.CreateTaskRequest.scheduled_date:type_name -> google.protobuf.Timestamp
	20, // 13: todoing.api.v1.CreateTaskResponse.response:type_name -> todoing.api.v1.Response
	3,  // 14: todoing.api.v1.CreateTaskResponse.task:type_name -> todoing.api.v1.Task
	21, // 15: todoing.api.v1.GetTasksRequest.pagination:type_name -> todoing.api.v1.PaginationRequest
	0,  // 16: todoing.api.v1.GetTasksRequest.status:type_name -> todoing.api.v1.TaskStatus
	1,  // 17: todoing.api.v1.GetTasksRequest.priority:type_name -> todoing.api.v1.TaskPriority
	20, // 18: todoing.api.v1.GetTasksResponse.response:type_name -> todoing.api.v1.Response
	3,  // 19: todoing.api.v1.GetTasksResponse.tasks:type_name -> todoing.api.v1.Task
	22, // 20: todoing.api.v1.GetTasksResponse.pagination:type_name -> todoing.api.v1.PaginationResponse
	20, // 21: todoing.api.v1.GetTaskResponse.response:type_name -> todoing.api.v1.Response
	3,  // 22: todoing.api.v1.GetTaskResponse.task:type_name -> todoing.api.v1.Task
	0,  // 23: todoing.api.v1.UpdateTaskRequest.status:type_name -> todoing.api.v1.TaskStatus
	1,  // 24: todoing.api.v1.UpdateTaskRequest.priority:type_name -> todoing.api.v1.TaskPriority
	19, // 25: todoing.api.v1.UpdateTaskRequest.deadline:type_name -> google.protobuf.Timestamp
	19, // 26: todoing.api.v1.UpdateTaskRequest.scheduled_date:type_name -> google.protobuf.Timestamp
	2,  // 27: todoing.api.v1.UpdateTaskRequest.comments:type_name -> todoing.api.v1.TaskComment
	20, // 28: todoing.api.v1.UpdateTaskResponse.response:type_name -> todoing.api.v1.Response
	3,  // 29: todoing.api.v1.UpdateTaskResponse.task:type_name -> todoing.api.v1.Task
	3,  // 30: todoing.api.v1.PriorityTask.task:type_name -> todoing.api.v1.Task
	19, // 31: todoing.api.v1.TaskSortConfig.created_at:type_name -> google.protobuf.Timestamp
	19, // 32: todoing.api.v1.TaskSortConfig.updated_at:type_name -> google.protobuf.Timestamp
	20, // 33: todoing.api.v1.UpdateTaskSortConfigResponse.response:type_name -> todoing.api.v1.Response
	14, // 34: todoing.api.v1.UpdateTaskSortConfigResponse.config:type_name -> todoing.api.v1.TaskSortConfig
	20, // 35: todoing.api.v1.GetTaskSortConfigResponse.response:type_name -> todoing.api.v1.Response
	14, // 36: todoing.api.v1.GetTaskSortConfigResponse.config:type_name -> todoing.api.v1.TaskSortConfig
	4,  // 37: todoing.api.v1.TaskService.CreateTask:input_type -> todoing.api.v1.CreateTaskRequest
	6,  // 38: todoing.api.v1.TaskService.GetTasks:input_type -> todoing.api.v1.GetTasksRequest
	8,  // 39: todoing.api.v1.TaskService.GetTask:input_type -> todoing.api.v1.GetTaskRequest
	10, // 40: todoing.api.v1.TaskService.UpdateTask:input_type -> todoing.api.v1.UpdateTaskRequest
	12, // 41: todoing.api.v1.TaskService.DeleteTask:input_type -> todoing.api.v1.DeleteTaskRequest
	17, // 42: todoing.api.v1.TaskService.GetTaskSortConfig:input_type -> todoing.api.v1.GetTaskSortConfigRequest
	15, // 43: todoing.api.v1.TaskService.UpdateTaskSortConfig:input_type -> todoing.api.v1.UpdateTaskSortConfigRequest
	5,  // 44: todoing.api.v1.TaskService.CreateTask:output_type -> todoing.api.v1.CreateTaskResponse
	7,  // 45: todoing.api.v1.TaskService.GetTasks:output_type -> todoing.api.v1.GetTasksResponse
	9,  // 46: todoing.api.v1.TaskService.GetTask:output_type -> todoing.api.v1.GetTaskResponse
	11, // 47: todoing.api.v1.TaskService.UpdateTask:output_type -> todoing.api.v1.UpdateTaskResponse
	20, // 48: todoing.api.v1.TaskService.DeleteTask:output_type -> todoing.api.v1.Response
	18, // 49: todoing.api.v1.TaskService.GetTaskSortConfig:output_type -> todoing.api.v1.GetTaskSortConfigResponse
	16, // 50: todoing.api.v1.TaskService.UpdateTaskSortConfig:output_type -> todoing.api.v1.UpdateTaskSortConfigResponse
	44, // [44:51] is the sub-list for method output_type
	37, // [37:44] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		EnumInfos:         file_task_proto_enumTypes,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
