// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.5
// source: unified.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 统一聚合条目
type UnifiedItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source           string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // task | event | reminder
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ScheduledAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	CountdownSeconds int32                  `protobuf:"varint,5,opt,name=countdown_seconds,json=countdownSeconds,proto3" json:"countdown_seconds,omitempty"`
	DaysLeft         int32                  `protobuf:"varint,6,opt,name=days_left,json=daysLeft,proto3" json:"days_left,omitempty"`
	Importance       int32                  `protobuf:"varint,7,opt,name=importance,proto3" json:"importance,omitempty"`
	PriorityScore    float64                `protobuf:"fixed64,8,opt,name=priority_score,json=priorityScore,proto3" json:"priority_score,omitempty"`
	RelatedEventId   string                 `protobuf:"bytes,9,opt,name=related_event_id,json=relatedEventId,proto3" json:"related_event_id,omitempty"`
	DetailUrl        string                 `protobuf:"bytes,10,opt,name=detail_url,json=detailUrl,proto3" json:"detail_url,omitempty"`
	SourceId         string                 `protobuf:"bytes,11,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	IsUnscheduled    bool                   `protobuf:"varint,12,opt,name=is_unscheduled,json=isUnscheduled,proto3" json:"is_unscheduled,omitempty"` // 与后端未安排任务逻辑对齐
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UnifiedItem) Reset() {
	*x = UnifiedItem{}
	mi := &file_unified_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedItem) ProtoMessage() {}

func (x *UnifiedItem) ProtoReflect() protoreflect.Message {
	mi := &file_unified_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedItem.ProtoReflect.Descriptor instead.
func (*UnifiedItem) Descriptor() ([]byte, []int) {
	return file_unified_proto_rawDescGZIP(), []int{0}
}

func (x *UnifiedItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnifiedItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UnifiedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UnifiedItem) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *UnifiedItem) GetCountdownSeconds() int32 {
	if x != nil {
		return x.CountdownSeconds
	}
	return 0
}

func (x *UnifiedItem) GetDaysLeft() int32 {
	if x != nil {
		return x.DaysLeft
	}
	return 0
}

func (x *UnifiedItem) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *UnifiedItem) GetPriorityScore() float64 {
	if x != nil {
		return x.PriorityScore
	}
	return 0
}

func (x *UnifiedItem) GetRelatedEventId() string {
	if x != nil {
		return x.RelatedEventId
	}
	return ""
}

func (x *UnifiedItem) GetDetailUrl() string {
	if x != nil {
		return x.DetailUrl
	}
	return ""
}

func (x *UnifiedItem) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *UnifiedItem) GetIsUnscheduled() bool {
	if x != nil {
		return x.IsUnscheduled
	}
	return false
}

// Upcoming 请求
type GetUnifiedUpcomingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hours         int32                  `protobuf:"varint,1,opt,name=hours,proto3" json:"hours,omitempty"`    // 默认72
	Sources       []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"` // task,event,reminder
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`    // 默认50
	Debug         bool                   `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`    // 是否包含调试
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnifiedUpcomingRequest) Reset() {
	*x = GetUnifiedUpcomingRequest{}
	mi := &file_unified_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnifiedUpcomingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnifiedUpcomingRequest) ProtoMessage() {}

func (x *GetUnifiedUpcomingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unified_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnifiedUpcomingRequest.ProtoReflect.Descriptor instead.
func (*GetUnifiedUpcomingRequest) Descriptor() ([]byte, []int) {
	return file_unified_proto_rawDescGZIP(), []int{1}
}

func (x *GetUnifiedUpcomingRequest) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *GetUnifiedUpcomingRequest) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *GetUnifiedUpcomingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUnifiedUpcomingRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

// 统计分布
type UnifiedUpcomingStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         int32                  `protobuf:"varint,1,opt,name=tasks,proto3" json:"tasks,omitempty"`
	Events        int32                  `protobuf:"varint,2,opt,name=events,proto3" json:"events,omitempty"`
	Reminders     int32                  `protobuf:"varint,3,opt,name=reminders,proto3" json:"reminders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedUpcomingStats) Reset() {
	*x = UnifiedUpcomingStats{}
	mi := &file_unified_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedUpcomingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedUpcomingStats) ProtoMessage() {}

func (x *UnifiedUpcomingStats) ProtoReflect() protoreflect.Message {
	mi := &file_unified_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedUpcomingStats.ProtoReflect.Descriptor instead.
func (*UnifiedUpcomingStats) Descriptor() ([]byte, []int) {
	return file_unified_proto_rawDescGZIP(), []int{2}
}

func (x *UnifiedUpcomingStats) GetTasks() int32 {
	if x != nil {
		return x.Tasks
	}
	return 0
}

func (x *UnifiedUpcomingStats) GetEvents() int32 {
	if x != nil {
		return x.Events
	}
	return 0
}

func (x *UnifiedUpcomingStats) GetReminders() int32 {
	if x != nil {
		return x.Reminders
	}
	return 0
}

// 调试信息
type UnifiedUpcomingWindowCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deadline      int32                  `protobuf:"varint,1,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Scheduled     int32                  `protobuf:"varint,2,opt,name=scheduled,proto3" json:"scheduled,omitempty"`
	DueDateOnly   int32                  `protobuf:"varint,3,opt,name=due_date_only,json=dueDateOnly,proto3" json:"due_date_only,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedUpcomingWindowCounts) Reset() {
	*x = UnifiedUpcomingWindowCounts{}
	mi := &file_unified_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedUpcomingWindowCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedUpcomingWindowCounts) ProtoMessage() {}

func (x *UnifiedUpcomingWindowCounts) ProtoReflect() protoreflect.Message {
	mi := &file_unified_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedUpcomingWindowCounts.ProtoReflect.Descriptor instead.
func (*UnifiedUpcomingWindowCounts) Descriptor() ([]byte, []int) {
	return file_unified_proto_rawDescGZIP(), []int{3}
}

func (x *UnifiedUpcomingWindowCounts) GetDeadline() int32 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *UnifiedUpcomingWindowCounts) GetScheduled() int32 {
	if x != nil {
		return x.Scheduled
	}
	return 0
}

func (x *UnifiedUpcomingWindowCounts) GetDueDateOnly() int32 {
	if x != nil {
		return x.DueDateOnly
	}
	return 0
}

func (x *UnifiedUpcomingWindowCounts) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UnifiedUpcomingDebug struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	GraceDays         int32                        `protobuf:"varint,1,opt,name=grace_days,json=graceDays,proto3" json:"grace_days,omitempty"`
	Hours             int32                        `protobuf:"varint,2,opt,name=hours,proto3" json:"hours,omitempty"`
	Now               string                       `protobuf:"bytes,3,opt,name=now,proto3" json:"now,omitempty"`
	End               string                       `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	WindowFilter      map[string]string            `protobuf:"bytes,5,rep,name=window_filter,json=windowFilter,proto3" json:"window_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 简化
	UnscheduledFilter map[string]string            `protobuf:"bytes,6,rep,name=unscheduled_filter,json=unscheduledFilter,proto3" json:"unscheduled_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WindowCounts      *UnifiedUpcomingWindowCounts `protobuf:"bytes,7,opt,name=window_counts,json=windowCounts,proto3" json:"window_counts,omitempty"`
	AddedUnscheduled  int32                        `protobuf:"varint,8,opt,name=added_unscheduled,json=addedUnscheduled,proto3" json:"added_unscheduled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnifiedUpcomingDebug) Reset() {
	*x = UnifiedUpcomingDebug{}
	mi := &file_unified_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedUpcomingDebug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedUpcomingDebug) ProtoMessage() {}

func (x *UnifiedUpcomingDebug) ProtoReflect() protoreflect.Message {
	mi := &file_unified_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedUpcomingDebug.ProtoReflect.Descriptor instead.
func (*UnifiedUpcomingDebug) Descriptor() ([]byte, []int) {
	return file_unified_proto_rawDescGZIP(), []int{4}
}

func (x *UnifiedUpcomingDebug) GetGraceDays() int32 {
	if x != nil {
		return x.GraceDays
	}
	return 0
}

func (x *UnifiedUpcomingDebug) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *UnifiedUpcomingDebug) GetNow() string {
	if x != nil {
		return x.Now
	}
	return ""
}

func (x *UnifiedUpcomingDebug) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *UnifiedUpcomingDebug) GetWindowFilter() map[string]string {
	if x != nil {
		return x.WindowFilter
	}
	return nil
}

func (x *UnifiedUpcomingDebug) GetUnscheduledFilter() map[string]string {
	if x != nil {
		return x.UnscheduledFilter
	}
	return nil
}

func (x *UnifiedUpcomingDebug) GetWindowCounts() *UnifiedUpcomingWindowCounts {
	if x != nil {
		return x.WindowCounts
	}
	return nil
}

func (x *UnifiedUpcomingDebug) GetAddedUnscheduled() int32 {
	if x != nil {
		return x.AddedUnscheduled
	}
	return 0
}

type GetUnifiedUpcomingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Response        *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Items           []*UnifiedItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Hours           int32                  `protobuf:"varint,3,opt,name=hours,proto3" json:"hours,omitempty"`
	Total           int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,5,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	Stats           *UnifiedUpcomingStats  `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	Debug           *UnifiedUpcomingDebug  `protobuf:"bytes,7,opt,name=debug,proto3" json:"debug,omitempty"` // 可空
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUnifiedUpcomingResponse) Reset() {
	*x = GetUnifiedUpcomingResponse{}
	mi := &file_unified_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnifiedUpcomingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnifiedUpcomingResponse) ProtoMessage() {}

func (x *GetUnifiedUpcomingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unified_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnifiedUpcomingResponse.ProtoReflect.Descriptor instead.
func (*GetUnifiedUpcomingResponse) Descriptor() ([]byte, []int) {
	return file_unified_proto_rawDescGZIP(), []int{5}
}

func (x *GetUnifiedUpcomingResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetUnifiedUpcomingResponse) GetItems() []*UnifiedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetUnifiedUpcomingResponse) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *GetUnifiedUpcomingResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetUnifiedUpcomingResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *GetUnifiedUpcomingResponse) GetStats() *UnifiedUpcomingStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetUnifiedUpcomingResponse) GetDebug() *UnifiedUpcomingDebug {
	if x != nil {
		return x.Debug
	}
	return nil
}

// Calendar
type GetUnifiedCalendarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Sources       []string               `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnifiedCalendarRequest) Reset() {
	*x = GetUnifiedCalendarRequest{}
	mi := &file_unified_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnifiedCalendarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnifiedCalendarRequest) ProtoMessage() {}

func (x *GetUnifiedCalendarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unified_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnifiedCalendarRequest.ProtoReflect.Descriptor instead.
func (*GetUnifiedCalendarRequest) Descriptor() ([]byte, []int) {
	return file_unified_proto_rawDescGZIP(), []int{6}
}

func (x *GetUnifiedCalendarRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetUnifiedCalendarRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *GetUnifiedCalendarRequest) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *GetUnifiedCalendarRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UnifiedCalendarItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	Importance    int32                  `protobuf:"varint,5,opt,name=importance,proto3" json:"importance,omitempty"`
	DetailUrl     string                 `protobuf:"bytes,6,opt,name=detail_url,json=detailUrl,proto3" json:"detail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedCalendarItem) Reset() {
	*x = UnifiedCalendarItem{}
	mi := &file_unified_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedCalendarItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedCalendarItem) ProtoMessage() {}

func (x *UnifiedCalendarItem) ProtoReflect() protoreflect.Message {
	mi := &file_unified_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedCalendarItem.ProtoReflect.Descriptor instead.
func (*UnifiedCalendarItem) Descriptor() ([]byte, []int) {
	return file_unified_proto_rawDescGZIP(), []int{7}
}

func (x *UnifiedCalendarItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnifiedCalendarItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UnifiedCalendarItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UnifiedCalendarItem) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *UnifiedCalendarItem) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *UnifiedCalendarItem) GetDetailUrl() string {
	if x != nil {
		return x.DetailUrl
	}
	return ""
}

type UnifiedCalendarDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Items         []*UnifiedCalendarItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedCalendarDay) Reset() {
	*x = UnifiedCalendarDay{}
	mi := &file_unified_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedCalendarDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedCalendarDay) ProtoMessage() {}

func (x *UnifiedCalendarDay) ProtoReflect() protoreflect.Message {
	mi := &file_unified_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedCalendarDay.ProtoReflect.Descriptor instead.
func (*UnifiedCalendarDay) Descriptor() ([]byte, []int) {
	return file_unified_proto_rawDescGZIP(), []int{8}
}

func (x *UnifiedCalendarDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UnifiedCalendarDay) GetItems() []*UnifiedCalendarItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetUnifiedCalendarResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Response        *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Year            int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month           int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	Days            []*UnifiedCalendarDay  `protobuf:"bytes,4,rep,name=days,proto3" json:"days,omitempty"`
	Total           int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,6,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUnifiedCalendarResponse) Reset() {
	*x = GetUnifiedCalendarResponse{}
	mi := &file_unified_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnifiedCalendarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnifiedCalendarResponse) ProtoMessage() {}

func (x *GetUnifiedCalendarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unified_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnifiedCalendarResponse.ProtoReflect.Descriptor instead.
func (*GetUnifiedCalendarResponse) Descriptor() ([]byte, []int) {
	return file_unified_proto_rawDescGZIP(), []int{9}
}

func (x *GetUnifiedCalendarResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetUnifiedCalendarResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetUnifiedCalendarResponse) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *GetUnifiedCalendarResponse) GetDays() []*UnifiedCalendarDay {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *GetUnifiedCalendarResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetUnifiedCalendarResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

var File_unified_proto protoreflect.FileDescriptor

const file_unified_proto_rawDesc = "" +
	"\n" +
	"\runified.proto\x12\x0etodoing.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xa8\x03\n" +
	"\vUnifiedItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12=\n" +
	"\fscheduled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12+\n" +
	"\x11countdown_seconds\x18\x05 \x01(\x05R\x10countdownSeconds\x12\x1b\n" +
	"\tdays_left\x18\x06 \x01(\x05R\bdaysLeft\x12\x1e\n" +
	"\n" +
	"importance\x18\a \x01(\x05R\n" +
	"importance\x12%\n" +
	"\x0epriority_score\x18\b \x01(\x01R\rpriorityScore\x12(\n" +
	"\x10related_event_id\x18\t \x01(\tR\x0erelatedEventId\x12\x1d\n" +
	"\n" +
	"detail_url\x18\n" +
	" \x01(\tR\tdetailUrl\x12\x1b\n" +
	"\tsource_id\x18\v \x01(\tR\bsourceId\x12%\n" +
	"\x0eis_unscheduled\x18\f \x01(\bR\risUnscheduled\"w\n" +
	"\x19GetUnifiedUpcomingRequest\x12\x14\n" +
	"\x05hours\x18\x01 \x01(\x05R\x05hours\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05debug\x18\x04 \x01(\bR\x05debug\"b\n" +
	"\x14UnifiedUpcomingStats\x12\x14\n" +
	"\x05tasks\x18\x01 \x01(\x05R\x05tasks\x12\x16\n" +
	"\x06events\x18\x02 \x01(\x05R\x06events\x12\x1c\n" +
	"\treminders\x18\x03 \x01(\x05R\treminders\"\x91\x01\n" +
	"\x1bUnifiedUpcomingWindowCounts\x12\x1a\n" +
	"\bdeadline\x18\x01 \x01(\x05R\bdeadline\x12\x1c\n" +
	"\tscheduled\x18\x02 \x01(\x05R\tscheduled\x12\"\n" +
	"\rdue_date_only\x18\x03 \x01(\x05R\vdueDateOnly\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"\xbe\x04\n" +
	"\x14UnifiedUpcomingDebug\x12\x1d\n" +
	"\n" +
	"grace_days\x18\x01 \x01(\x05R\tgraceDays\x12\x14\n" +
	"\x05hours\x18\x02 \x01(\x05R\x05hours\x12\x10\n" +
	"\x03now\x18\x03 \x01(\tR\x03now\x12\x10\n" +
	"\x03end\x18\x04 \x01(\tR\x03end\x12[\n" +
	"\rwindow_filter\x18\x05 \x03(\v26.todoing.api.v1.UnifiedUpcomingDebug.WindowFilterEntryR\fwindowFilter\x12j\n" +
	"\x12unscheduled_filter\x18\x06 \x03(\v2;.todoing.api.v1.UnifiedUpcomingDebug.UnscheduledFilterEntryR\x11unscheduledFilter\x12P\n" +
	"\rwindow_counts\x18\a \x01(\v2+.todoing.api.v1.UnifiedUpcomingWindowCountsR\fwindowCounts\x12+\n" +
	"\x11added_unscheduled\x18\b \x01(\x05R\x10addedUnscheduled\x1a?\n" +
	"\x11WindowFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\x16UnscheduledFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x02\n" +
	"\x1aGetUnifiedUpcomingResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x121\n" +
	"\x05items\x18\x02 \x03(\v2\x1b.todoing.api.v1.UnifiedItemR\x05items\x12\x14\n" +
	"\x05hours\x18\x03 \x01(\x05R\x05hours\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12)\n" +
	"\x10server_timestamp\x18\x05 \x01(\x03R\x0fserverTimestamp\x12:\n" +
	"\x05stats\x18\x06 \x01(\v2$.todoing.api.v1.UnifiedUpcomingStatsR\x05stats\x12:\n" +
	"\x05debug\x18\a \x01(\v2$.todoing.api.v1.UnifiedUpcomingDebugR\x05debug\"u\n" +
	"\x19GetUnifiedCalendarRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x18\n" +
	"\asources\x18\x03 \x03(\tR\asources\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xd1\x01\n" +
	"\x13UnifiedCalendarItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12=\n" +
	"\fscheduled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12\x1e\n" +
	"\n" +
	"importance\x18\x05 \x01(\x05R\n" +
	"importance\x12\x1d\n" +
	"\n" +
	"detail_url\x18\x06 \x01(\tR\tdetailUrl\"c\n" +
	"\x12UnifiedCalendarDay\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x129\n" +
	"\x05items\x18\x02 \x03(\v2#.todoing.api.v1.UnifiedCalendarItemR\x05items\"\xf5\x01\n" +
	"\x1aGetUnifiedCalendarResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.todoing.api.v1.ResponseR\bresponse\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\x126\n" +
	"\x04days\x18\x04 \x03(\v2\".todoing.api.v1.UnifiedCalendarDayR\x04days\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\x12)\n" +
	"\x10server_timestamp\x18\x06 \x01(\x03R\x0fserverTimestamp2\xea\x01\n" +
	"\x0eUnifiedService\x12k\n" +
	"\x12GetUnifiedUpcoming\x12).todoing.api.v1.GetUnifiedUpcomingRequest\x1a*.todoing.api.v1.GetUnifiedUpcomingResponse\x12k\n" +
	"\x12GetUnifiedCalendar\x12).todoing.api.v1.GetUnifiedCalendarRequest\x1a*.todoing.api.v1.GetUnifiedCalendarResponseB5Z3github.com/axfinn/todoIngPlus/backend-go/pkg/api/v1b\x06proto3"

var (
	file_unified_proto_rawDescOnce sync.Once
	file_unified_proto_rawDescData []byte
)

func file_unified_proto_rawDescGZIP() []byte {
	file_unified_proto_rawDescOnce.Do(func() {
		file_unified_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_unified_proto_rawDesc), len(file_unified_proto_rawDesc)))
	})
	return file_unified_proto_rawDescData
}

var file_unified_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_unified_proto_goTypes = []any{
	(*UnifiedItem)(nil),                 // 0: todoing.api.v1.UnifiedItem
	(*GetUnifiedUpcomingRequest)(nil),   // 1: todoing.api.v1.GetUnifiedUpcomingRequest
	(*UnifiedUpcomingStats)(nil),        // 2: todoing.api.v1.UnifiedUpcomingStats
	(*UnifiedUpcomingWindowCounts)(nil), // 3: todoing.api.v1.UnifiedUpcomingWindowCounts
	(*UnifiedUpcomingDebug)(nil),        // 4: todoing.api.v1.UnifiedUpcomingDebug
	(*GetUnifiedUpcomingResponse)(nil),  // 5: todoing.api.v1.GetUnifiedUpcomingResponse
	(*GetUnifiedCalendarRequest)(nil),   // 6: todoing.api.v1.GetUnifiedCalendarRequest
	(*UnifiedCalendarItem)(nil),         // 7: todoing.api.v1.UnifiedCalendarItem
	(*UnifiedCalendarDay)(nil),          // 8: todoing.api.v1.UnifiedCalendarDay
	(*GetUnifiedCalendarResponse)(nil),  // 9: todoing.api.v1.GetUnifiedCalendarResponse
	nil,                                 // 10: todoing.api.v1.UnifiedUpcomingDebug.WindowFilterEntry
	nil,                                 // 11: todoing.api.v1.UnifiedUpcomingDebug.UnscheduledFilterEntry
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
	(*Response)(nil),                    // 13: todoing.api.v1.Response
}
var file_unified_proto_depIdxs = []int32{
	12, // 0: todoing.api.v1.UnifiedItem.scheduled_at:type_name -> google.protobuf.Timestamp
	10, // 1: todoing.api.v1.UnifiedUpcomingDebug.window_filter:type_name -> todoing.api.v1.UnifiedUpcomingDebug.WindowFilterEntry
	11, // 2: todoing.api.v1.UnifiedUpcomingDebug.unscheduled_filter:type_name -> todoing.api.v1.UnifiedUpcomingDebug.UnscheduledFilterEntry
	3,  // 3: todoing.api.v1.UnifiedUpcomingDebug.window_counts:type_name -> todoing.api.v1.UnifiedUpcomingWindowCounts
	13, // 4: todoing.api.v1.GetUnifiedUpcomingResponse.response:type_name -> todoing.api.v1.Response
	0,  // 5: todoing.api.v1.GetUnifiedUpcomingResponse.items:type_name -> todoing.api.v1.UnifiedItem
	2,  // 6: todoing.api.v1.GetUnifiedUpcomingResponse.stats:type_name -> todoing.api.v1.UnifiedUpcomingStats
	4,  // 7: todoing.api.v1.GetUnifiedUpcomingResponse.debug:type_name -> todoing.api.v1.UnifiedUpcomingDebug
	12, // 8: todoing.api.v1.UnifiedCalendarItem.scheduled_at:type_name -> google.protobuf.Timestamp
	7,  // 9: todoing.api.v1.UnifiedCalendarDay.items:type_name -> todoing.api.v1.UnifiedCalendarItem
	13, // 10: todoing.api.v1.GetUnifiedCalendarResponse.response:type_name -> todoing.api.v1.Response
	8,  // 11: todoing.api.v1.GetUnifiedCalendarResponse.days:type_name -> todoing.api.v1.UnifiedCalendarDay
	1,  // 12: todoing.api.v1.UnifiedService.GetUnifiedUpcoming:input_type -> todoing.api.v1.GetUnifiedUpcomingRequest
	6,  // 13: todoing.api.v1.UnifiedService.GetUnifiedCalendar:input_type -> todoing.api.v1.GetUnifiedCalendarRequest
	5,  // 14: todoing.api.v1.UnifiedService.GetUnifiedUpcoming:output_type -> todoing.api.v1.GetUnifiedUpcomingResponse
	9,  // 15: todoing.api.v1.UnifiedService.GetUnifiedCalendar:output_type -> todoing.api.v1.GetUnifiedCalendarResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_unified_proto_init() }
func file_unified_proto_init() {
	if File_unified_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_unified_proto_rawDesc), len(file_unified_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unified_proto_goTypes,
		DependencyIndexes: file_unified_proto_depIdxs,
		MessageInfos:      file_unified_proto_msgTypes,
	}.Build()
	File_unified_proto = out.File
	file_unified_proto_goTypes = nil
	file_unified_proto_depIdxs = nil
}
